### ISSUE TITLE
Can't really set n_independant or n_shared to zero

### ISSUE THREAD

**Issue by Optimox** [dreamquark-ai/tabnet#105]
**Describe the bug**

**What is the current behavior?**
It's possible without error to train with `n_independent=0` and `n_shared=0` and looking at the code it seems that zero is actually 1, so minimal value is 1 and this should not be the case.

**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**

Well I guess 0 and 0 should throw a clear error, but 0 should mean 0.

**Screenshots**

**Other relevant information:**
poetry version:  
python version: 
Operating System: 
Additional tools:

**Additional context**

**Comment by Hartorn** [comment]
After looking at the code, I think the problem is especially on n_independent, that should accept value >=1

**Comment by Optimox** [comment]
yep created a PR, not finished yet
