### ISSUE TITLE
[Question/Feature Request] You mentioned it works with GPU, does Fast-TabNet work with TPUs?

### ISSUE THREAD

**Issue by neomatrix369** [dreamquark-ai/tabnet#129]
## Feature request

**What is the expected behavior?**
Same as the outcome on CPUs and GPUs

**What is motivation or use case for adding/changing the behaviour?**
Better training performance 

**How should this be implemented in your opinion?**
Similar to Tensorflow/Pytorch sends the data to the TPU 

**Are you willing to work on this yourself?**
Happy to contribute along with another experienced developer

**Comment by Optimox** [comment]
Hey @neomatrix369, I'm not sure to understand correctly the question?

fast-tabnet is the fastai wrapper of pytorch-tabnet, they are two different things.

Does fast-tabnet uses TPU : I don't think so.
Does pytorch-tabnet uses TPU: no.

I've never used pytorch with TPUs, so if you have some links in that direction I'd be interested to know more!

**Comment by neomatrix369** [comment]
> Hey @neomatrix369, I'm not sure to understand correctly the question?
> 
> fast-tabnet is the fastai wrapper of pytorch-tabnet, they are two different things.
> 
> Does fast-tabnet uses TPU : I don't think so.
> Does pytorch-tabnet uses TPU: no.
> 
> I've never used pytorch with TPUs, so if you have some links in that direction I'd be interested to know more!

Thanks for your response, I'm working on this notebook: https://www.kaggle.com/neomatrix369/bert-on-steroids-using-pytorch-cpus-tpus (credits to the inspirer of the notebook - mentioned in it).

It uses Pytorch, Bert, Transformers and TPUs on Kaggle (although should work on Google Colab as well) to do multi-processing TPU model training.

I hope this helps.
