### ISSUE TITLE
[Question/Feature Request] Any explainability output or examples available to try out

### ISSUE THREAD

**Issue by neomatrix369** [dreamquark-ai/tabnet#130]
## Feature request

**What is the expected behavior?**
No behaviour changes. Rather add examples to the docs or the examples section of the repo. 

**What is motivation or use case for adding/changing the behavior?**
Make it easy to allow users to adapt it into their ML workflow. As explainability is an important topic in the current atmosphere.

**How should this be implemented in your opinion?**
No implementation needed, just docs and examples either as a python code snippet, a Jupyter notebook or a Kaggle kernel will be sufficient.

**Are you willing to work on this yourself?**
yes

**Comment by eduardocarvp** [comment]
Hi @neomatrix369 ,

Our example/tutorial notebooks contain a special section for the explainability. If you have a look here https://github.com/dreamquark-ai/tabnet/blob/develop/census_example.ipynb , there is a section subtitled `Local explainability and masks` where we try to explain, for each input data line and for each step in the architecture, what are the mask values as well as the final `explain_matrix`.

Of course, if you have suggestions on how to better show these results or how to make them clearer we'd love to hear your feedback!

**Comment by neomatrix369** [comment]
Thank you for sharing the link, I will give it a whirl!
