### ISSUE TITLE
getting error while fit

### ISSUE THREAD

**Issue by Bharat9280** [dreamquark-ai/tabnet#131]
**Describe the bug**

 new() received an invalid combination of arguments - got (list, int), but expected one of:
 * (*, torch.device device)
      didn't match because some of the arguments have invalid types: (!list!, !int!)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**

**Screenshots**

**Other relevant information:**
poetry version:  
python version: 
Operating System: 
Additional tools:

**Additional context**

**Comment by Optimox** [comment]
hello @Bharat9280,

Could you please share a bit more about the issue you have?

What is the code that you are trying to run?

**Comment by Optimox** [comment]
Well @Bharat9280,

I'm closing this issue, feel free to reopen it when you have more info to share as there is no way to help you with so little info.
