### ISSUE TITLE
[Question/Feature Request] Any example of applying tabnet in reinforcement and self-supervised learning

### ISSUE THREAD

**Issue by andreipit** [dreamquark-ai/tabnet#134]
## Feature request

**What is the expected behavior?**
New example in the examples section of the repo.

**What is motivation or use case for adding/changing the behavior?**
Adding a new application area.

**How should this be implemented in your opinion?**
Just docs and examples of using tabnet with openai and small data.

**Are you willing to work on this yourself?**
Maybe. Not sure.

#Abhishek-eBook

**Comment by Optimox** [comment]
Hello @andreipit,

I am no expert in reinforcement learning but I don't think tabnet applies here, I don't think anyone applied tabnet to reinforcement learning yet.

As for  the self supervised learning part, the original paper is mentioning it and gives some results. This feature will probably be added in the future as I think it's an interesting idea for small datastes.

**Comment by rosefun** [comment]
Hi, can you add self-supervised learning function? I think it's useful as the train data usually contains missing value.

**Comment by Optimox** [comment]
Self supervision could be used for nan imputing but I think it’s really a side use of self-supervised pre-training.

But I agree that it would be an interesting feature, need to find some time to do this.
