### ISSUE TITLE
Create network on model instantiation

### ISSUE THREAD

**Issue by eduardocarvp** [dreamquark-ai/tabnet#138]
## Feature request

**What is the expected behavior?**
The network attribute should be created as soon as a model classifier or regressor is instantiated.

**What is motivation or use case for adding/changing the behavior?**
The network's existence is independent of the `fit` function and this will help with saving/loading features. None of the network parameters depend on any fit-only information. 

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by Optimox** [comment]
I left a comment here https://github.com/dreamquark-ai/tabnet/issues/136 but I think it belongs here :)
