### ISSUE TITLE
Using Pytorch-Tabnet as nn.Module blocks or torchvision models

### ISSUE THREAD

**Issue by tanulsingh** [dreamquark-ai/tabnet#142]
```
class Roberta(transformers.BertPreTrainedModel):
    def __init__(self, conf):
        super(TweetModel, self).__init__(conf)
        self.roberta = transformers.RobertaModel.from_pretrained(ROBERTA_PATH, config=conf)
        
        self.dropout = nn.Dropout(0.1)
        self.l0 = nn.Linear(768, 2)
  
        torch.nn.init.normal_(self.l0.weight, std=0.02)
        torch.nn.init.normal_(self.l1.weight, std=0.02) 
```

I want to do something like this with Tabnet and have my own custom model so that I have all the liberties of using a neural net and I don't have to do it like scikit learn again

**Comment by Optimox** [comment]
Hello @tanulsingh,

Basically the code is split into two files, `tab_model.py` and `tab_network.py`.

`tab_model.py` is dealing with the scikit-like part.

What you want is in the `tab_network.py` here is a dummy example (you can add any torch function in the architecture : 
```
from pytorch_tabnet.tab_network import TabNet, TabNetNoEmbeddings
class DoubleTabnet(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(DoubleTabnet, self).__init__()
        self.first_tabnet = TabNet(input_dim=input_dim,
                                   output_dim=output_dim)
        self.second_tabnet = TabNetNoEmbeddings(input_dim=output_dim,
                                               output_dim=output_dim)
        
    def forward(self, x):
        out = self.first_tabnet(x)
        out = self.second_tabnet(x)
        return out
``` 

You can use any class from this file `https://github.com/dreamquark-ai/tabnet/blob/develop/pytorch_tabnet/tab_network.py` by doing 

```
from pytorch_tabnet.tab_network import AttentiveTransformer, FeatTransformer, EmbeddingGenerator
```

Does this answer your question?

**Comment by Optimox** [comment]
well @tanulsingh,

I'm closing this, hope you'll soon share what you did with pytorch-tabnet on this repo.
