### ISSUE TITLE
What is the best way to access the categorical embedding layers for use in other models?

### ISSUE THREAD

**Issue by tmontana** [dreamquark-ai/tabnet#149]
## Feature request
Is there a way to get access to the embedding layers and download activations into a dataframe?

**What is the expected behavior?**

**What is motivation or use case for adding/changing the behavior?**
These embeddings can be used to get better numerical representations of categorical features (than say OHE) for use in other models.  They can also be used for the clustering of categorical features.

**How should this be implemented in your opinion?**
I'm not so familiar with Pytorch.  My guess is it's not very difficult but just need some instructions as to how to access different layers.

**Are you willing to work on this yourself?**
yes

Many thanks for this great repo!

**Comment by Optimox** [comment]
hello @tmontana,

There is no support for this feature but here is what you could do.

After fitting your model you can see the name and the shapes of all your embedding layers by doing 
```clf.network.embedder.embeddings```
Then for example if you want to see how the model represents category 10 of your 4th categorical feature you can do:
```
embedding_matrix_4 = clf.network.state_dict()["embedder.embeddings.4.weight"]
embedding_10 = embedding_matrix_4[10,:]
```

So by iterating over all your categorical columns you can retrieve all the embeddings.

Hope this helps, let me know if this does not solve your problem.

**Comment by tmontana** [comment]
Will try that.  Many thanks!

**Comment by Optimox** [comment]
well @tmontana let us know if it did not work and feel free to reopen this issue

**Comment by tmontana** [comment]
Hi all.  Sorry it took me a while.  This absolutely works.  My objective was to extract the embeddings given a particular dataset such that they could be used in place of OHE or simple numeric transform.

This would be similar to using scikit-learn style category encoders with fit/transform methods (see http://contrib.scikit-learn.org/category_encoders/index.html).

Is it fair to say that to transform a dataset I could use the embeddings from the model to map each category to it's row in the matrix of embeddings?  How would I obtain the mapping (ie embedded value for each row of the dataset)?

In the meantime I highly recommend Catboost Encoder (http://contrib.scikit-learn.org/category_encoders/catboost.html) as it made a huge positive difference in my experiments (I never liked OHE).

**Comment by Optimox** [comment]
Well once your model is trained the embeddings are fixed, so there is nothing specific to one row.

Category "dog" could be embedded to [0, 0.5, 0.25, 1.2] for exemple (emb_size=4 here) then it's the same embedding for every row in the dataset, so if you know how each category is mapped you can apply this to any row of your dataset.

But using tabnet just to use the embeddings seems an overkill.

CatBoost encoder is doing something really different as it's a smart target encoding. Note that you can use catboost encoder on you categorical variable before feeding your dataset to TabNet. Catboost encoder is indeed really powerful and it can improve performances of Tabnet on some datasets so feel free to use both!
