### ISSUE TITLE
Slack/discussion link is broken

### ISSUE THREAD

**Issue by ddofer** [dreamquark-ai/tabnet#159]
The [link ](https://mltooling.slack.com/join/shared_invite/zt-e4y14rbp-IReRxmjoNy27XQFQgh~4ZQ#/)from the main README to the slack discussion appears broken ("Link is no longer active"). 
For now, I opened a PR via a seperate branch (improvements to the example notebooks). Hopefully that's ok!

**Comment by Optimox** [comment]
Yeah right, I think the link expired, we'll need to change it in the README, but in the meantime you can access the slack using this https://join.slack.com/t/mltooling/shared_invite/zt-fxaj0qk7-SWy2_~EWyhj4x9SD6gbRvg let me know it that does not work either
