### ISSUE TITLE
How to fixed random initialization parameters?

### ISSUE THREAD

**Issue by rosefun** [dreamquark-ai/tabnet#165]
For the same network structure, the results of running for many times are quite different . I think the reason is that the initialization parameters are different each time.

So, do you consider fixed random initialization parameters of network?

**Comment by Optimox** [comment]
Random seeds are already fixed, in all the experiments I did (either on CPU or GPU)  you can reproduce the exact same results.
Could you share more information like a reproducible code snippet and your environment?

Do you have some preprocessing steps? Do they involve random splits, random shuffle?

**Comment by Optimox** [comment]
Well I'm closing this since I can't reproduce your error, feel free to reopen with more info when you have some.
