### ISSUE TITLE
It seems that the network is not suitable when the number of features is large?

### ISSUE THREAD

**Issue by rosefun** [dreamquark-ai/tabnet#166]
I test the TabNet model with dataset, where there are about `900` feature columns and about `800,000` training samples. The model will always overfit and early stopping, though I have set `n_step=1,n_a=n_b=4`. 

Finally, I check the important features, it seems that only few features have high score, and others' scores are low.
 
f1	0.3901934456720641
f2	0.1910946405238988
f3	0.18153149253617776
f4	0.10164209615198923
f5	0.020720944593584867
f6	0.017847015485666733
f7	0.008139174984953694
f8	0.0062732777212831025
f9	0.006175457271420507
f10	0.005488134122991516

Any suggestions or opinion about it?

**Comment by Optimox** [comment]
Hello, thanks for sharing.

I think I miss some information to help you:
Is this a public dataset? Could you share it with the community? What kind of problem is this? How does tabnet compares with other models?

However what I can tell from what I know:
- tabnet should work ok with large number of features
- try bigger n_a and n_d : you are creating a bottle neck from 900 to n_d so it’s probably too hard for the model to compress info that much
- try more steps: with only one step tabnet is closer to an MLP, steps from 3 to 10 could yield better results
- try to reduce lambda_sparse parameter, this parameter is making the mask sparser, so with 1 step it’s likely that the model will use only few features - try lambda_sparse=0 first and see if it has an impact
- if you add more steps then try to set the gamma parameter closer to one, like 1.0 or 1.1 and this should force the model to use different features at each steps

Let me know if it help!

**Comment by Optimox** [comment]
Well feel free to come back to us with more info and reopen this issue if needed
