### ISSUE TITLE
Training speed is very slow.

### ISSUE THREAD

**Issue by abditag2** [dreamquark-ai/tabnet#172]
## Feature request
This more of a discussion point rather than a feature request. We observed that the training of TabNet is very vert slow which makes sense given the sequential nature of the model. I want to make sure that others have experienced the same slow training speed and if there is anything to mitigate it?

**What is the expected behavior?**
NA

**What is motivation or use case for adding/changing the behavior?**
NA

**How should this be implemented in your opinion?**
Reducing the number of sequential blocks will increase training speed but will impact the performance of the model.

**Are you willing to work on this yourself?**
yes

**Comment by Optimox** [comment]
Well I guess you’ll need to define « slow », « very » and « very very slow » if you want someone to relate.

What is your training time? on which dataset? What is your setup?

**Comment by Optimox** [comment]
well feel free to reopen with new piece of information!
