### ISSUE TITLE
How to pretrain models?

### ISSUE THREAD

**Issue by yiyiyi4321** [dreamquark-ai/tabnet#178]
## Feature request

**What is the expected behavior?**
pretrain models

**What is motivation or use case for adding/changing the behavior?**
This behavior is mentioned in this paper

**How should this be implemented in your opinion?**
A function like  pretrain

**Are you willing to work on this yourself?**
yes

**Comment by Optimox** [comment]
Hi @yiyiyi4321,

Do you mean unsupervised pretraining?

This has not been implemented yet but it’s high in the priority list. Hopefully I’ll have time to implement it in the coming month!

**Comment by yiyiyi4321** [comment]
ok, Thank you!

**Comment by vantony1** [comment]
Any update on this @Optimox ?

**Comment by Optimox** [comment]
@vantony1 

yes there's a PR coming soon #220 

Here's a Kaggle notebook showing what it will look like : https://www.kaggle.com/optimo/selfsupervisedtabnet
