### ISSUE TITLE
Unsupervised pretraining

### ISSUE THREAD

**Issue by kkontoudi** [dreamquark-ai/tabnet#187]
## Feature request
I think there is no way to do unsupervised pretraining in the implementation.Please correct me if I am wrong.

**What is the expected behavior?**
Having a way to do pretraining before the classification or regression task.

**What is motivation or use case for adding/changing the behavior?**
The original paper of TabNet

**How should this be implemented in your opinion?**
I haven't studied the code base yet but I think it would be nice to have a Pretrainer class in addition to the classifier and regressor classes.
Then one would take the pretrained model and use it to initialise a classifier/regressor.

**Are you willing to work on this yourself?**
yes

**Comment by Optimox** [comment]
Yes you are right, this is not available yet.

The unsupervised training part has been added later in the revised version of the paper, so we did not implement it initially.

I think it's a good feature to add but I had a look at the paper recently and it's not very clear how do they perform this. There are a lot of different interpretation from the little information given, so I think it's not such an easy feature to implement.

I can't promise anything but I'll try to think about this feature in the near future, feel free to propose something through a PR if you like

**Comment by kkontoudi** [comment]
Hello,

Thanks for the very quick reply. I will start studying more in depth and work on an implementation but I cannot promise anything (yet). Do you have some guidelines for contributions?

And BTW awesome work on this library (I didn't say it on my first message)

**Comment by Optimox** [comment]
Hey!

Good to know that you want to contribute!

About the guidelines, they are pretty standard:
- you’ll need to pass the CI
- it would be good to have a notebook example on this feature
- code changes should be minimal
- number of commits should be minimal and their naming should be clear and follow  «feat: anything you want »
- feel free to create your PR early and mark it as WIP so that we can discuss about it before hand 

Thanks and good luck!

**Comment by EvilPsyCHo** [comment]
I was also curious about this,  Optmox build a great project , clean code and model performence meet expectation in my task.
but as paper show, using pre-unsupervised-training can improve a big gap.

**Comment by EvilPsyCHo** [comment]
Is there any progress or ideas in this issue?

**Comment by kkontoudi** [comment]
Hello,

I've made some progress on the implementation (defining a TabNetPretrainer network) but there is still work to be done to implement the model class.
@Optimox let me know if you want me to already open a PR and maybe give some details about how I see the next steps. The latest refactoring will be of great help as I need to reinitialize the priors at every epoch.

**Comment by Optimox** [comment]
Hello @kkontoudi,
Timing is not the best for you, I just started a PR #220 with @eduardocarvp to implement self supervised pretraining.
But feel free to open a PR to share your implementation so that we can discuss about it.

@EvilPsyCHo as you can see, we're making some progress yes! :)

**Comment by kkontoudi** [comment]
I have opened a PR https://github.com/dreamquark-ai/tabnet/pull/221 with what I have done so far. It is actually very similar to what you have in your PR  https://github.com/dreamquark-ai/tabnet/pull/220 @Optimox. 
Feel free to close my PR once you have a look and let me know if we can somehow join efforts.
