### ISSUE TITLE
`load_model` method is not working

### ISSUE THREAD

**Issue by Ankur-singh** [dreamquark-ai/tabnet#190]
**Describe the bug**

When you try to load a model after training, you get an `UnsupportedOperations` error.

**What is the current behavior?**
When try to load the model, it gives an error.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a model
2. Train the model and save it
3. Try loading the model again

**Expected behavior**
It should load the model without any error.

**Screenshots**

**Other relevant information:**
poetry version:  
python version: 
Operating System: 
Additional tools:

**Additional context**

**Comment by Optimox** [comment]
Hello this has already been pointed here #163 
It has been solved already in develop branch, you have 3 options:
- switch to develop
- switch to python 3.7
- wait for next release

Feel free to reopen and give more information if you think that this is not related.

**Comment by Ankur-singh** [comment]
Thanks @Optimox. I will give it a try.
