### ISSUE TITLE
A problem of not setting validation set 

### ISSUE THREAD

**Issue by ZacheryAU** [dreamquark-ai/tabnet#191]
Hi, 
Thanks for the great job of reproducing TabNet. I tried it on our project and as our train-test division is inflexible so that validation set were not set. Then the problem happened:
`assert X_train.shape[1] == X_valid.shape[1], "Dimension mismatch X_train X_valid"`
as X_valid is None, the error occurred : AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Optimox** [comment]
hey @ZacheryAU,

It's true that at the moment we don't allow not to have a validation set explicitly given, but it's quite easy to overcome:
1- simply pass your training set as a validation set and everything will run ok (then you'll need to decide the number of epochs to train as early stopping won't work correctly)
2- or split your training with a kfold to get a validation set

**Comment by Optimox** [comment]
This is now solved by #193, you'll need either to use develop branch or wait for the next release which should come soon!
