### ISSUE TITLE
Docstring edits

### ISSUE THREAD

**Issue by jrfiedler** [dreamquark-ai/tabnet#203]
I'm offering to edit docstrings in a new PR. I think I saw that this repo encourages opening issues before PRs.

**Describe the bug**

Docstrings have a variety of minor issues. Some examples:
- docstring has wrong parameter name ([example](https://github.com/dreamquark-ai/tabnet/blob/develop/pytorch_tabnet/metrics.py#L281))
- indentation isn't standard NumPy format ([example](https://github.com/dreamquark-ai/tabnet/blob/develop/pytorch_tabnet/abstract_model.py#L96))
- return value isn't listed ([example](https://github.com/dreamquark-ai/tabnet/blob/develop/pytorch_tabnet/abstract_model.py#L278))

**What is the current behavior?**

N/A

**If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**Expected behavior**

N/A

**Screenshots**

N/A

**Other relevant information:**

N/A

**Additional context**

N/A

**Comment by eduardocarvp** [comment]
Hi @jrfiedler, thank you for your issue!
Sure, this would be great! We wish to have a Sphinx documentation page and this would help us a lot. So go ahead, we can merge it as soon as it's done :)

Could you keep the numpy-style for the docstrings?
