### ISSUE TITLE
load_model map_location not replicated to Py3.6 fallback branch

### ISSUE THREAD

**Issue by athewsey** [dreamquark-ai/tabnet#204]
**Describe the bug**

The recently-added `map_location` pass-through to `torch.load()` (from c2b560e72bc01e34e8dba7578f239e37bbd6782c) was not replicated to the Python 3.6 fallback branch of the code - so in Py36 we are unable to load a model trained on GPU in a CPU-only environment.

**What is the current behavior?**

Cannot `load_model()` in a Python 3.6, CPU-only environment if the saved model was trained on GPU.

Error message from `torch.load()`:

```
Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Train a model on CUDA/GPU device
2. `save_model()`
3. Copy the artifact to a CPU-only environment (no CUDA)
4. Load the model with`load_model()`

**Expected behavior**

The same parameters passed to `torch.load()` in the standard branch as in the Python 3.6 exception branch of the code: Enabling the library to successfully load the model with mapping to CPU.

**Screenshots**

N/A

**Other relevant information:**
poetry version:  N/A
python version: 3.6
Operating System: Linux (Ubuntu-based, per the [PyTorch v1.4 DLC doc](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#prior-versions))
Additional tools: Amazon SageMaker, PyTorch v1.4

**Additional context**

N/A

**Comment by Optimox** [comment]
Thank you, I'll merge your fix as soon as the CI finished!

**Comment by athewsey** [comment]
I wonder if it would be feasible or desirable to modify CircleCI config so that some tests run on different Python versions, as a lightweight way to try and protect against regressions / drive robustness? Seems like it might be possible to define additional executor containers, but IDK if there are cost implications or anything for doing that...

**Comment by Optimox** [comment]
I think this would indeed be feasible, it would simply make the CI longer. But why not! @Hartorn ?
