### ISSUE TITLE
Specifying device

### ISSUE THREAD

**Issue by psinger** [dreamquark-ai/tabnet#206]
It is impossible to manually specify the device:

`UnboundLocalError: local variable 'device_name' referenced before assignment`

The reason seems to be this line:
https://github.com/dreamquark-ai/tabnet/blob/develop/pytorch_tabnet/abstract_model.py#L70

**Comment by Optimox** [comment]
Thanks @psinger, looks like the refacto introduced some bugs, I'm on it!

**Comment by psinger** [comment]
Thanks - it seems that the code still uses GPU through pin memory when using CPU.

**Comment by Optimox** [comment]
@psinger thanks for pointing out.

I thought pin_memory would be disable automatically by pytorch if tensors are on cpu.
You can set pin_memory to False in the model parameters.

In your opinion, should we set default pin_memory to False? Or automatically switch to False when using cpu?

**Comment by psinger** [comment]
I believe an additional False setting when using CPU makes sense, should not hurt in any way.

**Comment by Optimox** [comment]
ok thank you, will make the update
