### ISSUE TITLE
TypeError: ufunc 'isinf'/'isnan' not supported for the input types

### ISSUE THREAD

**Issue by MtDersvan** [dreamquark-ai/tabnet#214]
**Describe the bug**
During `fit()` the `check_nans()` function throws the following errors:
~~~
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
~~~

~~~
TypeError: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
~~~

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
Train features are of type {dtype('int64'), dtype('float64')}
Labels are of type {dtype('O')} // <- this is probably the issue, as the labels are strings, though all estimators support labels as strings and the model trains just fine without `check_nans()`.

**Expected behavior**
There are no `nan` & `inf` in the dataset, so the training works when the function is ignored.
When np.nan is replaced with pd.isnull - the first issue doesn't show up.

python version: 3.8
Operating System: Ubuntu 16.04

**Comment by Optimox** [comment]
Hello @MtDersvan,

I've run through this error before, it's not really a bug but an unclear error.
I think you might have some booleans in your training set, numpy won't allow to `np.isnan` on this. If you make sure to convert boolean into int or float you should be all right.

Let me know if this solves your problem.

I'll think of a way to avoid this.

**Comment by Optimox** [comment]
Thanks @MtDersvan,

Looks like I accidently killed this feature with the check nan, I'll correct that. Thank you!
In the meantime you could probably label encode your targets.
