### ISSUE TITLE
Support in per sample weight

### ISSUE THREAD

**Issue by RoyHirsch** [dreamquark-ai/tabnet#216]
## Feature request

**What is the expected behavior?**
Adding an option for per samples weight - useful for many scenarios with imbalance dataset

**What is motivation or use case for adding/changing the behavior?**
Imbalance datasets

**How should this be implemented in your opinion?**
Custom loss_func, change the call for calc the loss and support new arguments at "fit" (like in xgboost)

**Are you willing to work on this yourself?**
yes

**Comment by kmedved** [comment]
Isn't this already supported per #145?

**Comment by RoyHirsch** [comment]
The current "weights" implementation is referring to "per class" weights.
My intention is to support "per sample" weights.
As in xgboost sample_weight 
https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.XGBClassifier.fit

There are many scenarios where this is needed (sample weight is supported in all DT implementations)

**Comment by Optimox** [comment]
Hello @RoyHirsch,

As mentioned by @kmedved, per sample weight is already available.
For classfication weights can be:
- 0 : no weight sampling
- 1 : balanced weight sampling
- dict : per class weight
- np.array : per sample weight

For regression and multitask, only per sample weight is allowed.


What's your use case?

**Comment by Optimox** [comment]
Closing this, feel free to reopen if we missed something.
