### ISSUE TITLE
Window 10x slower

### ISSUE THREAD

**Issue by noklam** [dreamquark-ai/tabnet#225]
I am experiencing roughly 10x slower if I run this on Window. It still print cuda: True but I suspect it is not really using the GPU since the speed is roughly the same as I run with CPU.

**Comment by eduardocarvp** [comment]
Hi @noklam , thank you for the issue.
I don't have a Windows machine I could use to test, do you @Optimox ?

**Comment by Optimox** [comment]
@eduardocarvp nope...

Honnestly the only reason this could be slower in Windows is pytorch vs Windows. I don't see anything we can do about it.
@noklam are you comparing from the same machine? I don't see why Windows would make it slower to be honest.

**Comment by noklam** [comment]
On Linux
![image](https://user-images.githubusercontent.com/18221871/97854424-654d4600-1d34-11eb-9c20-88adec762942.png)
On Window
![image](https://user-images.githubusercontent.com/18221871/97854442-6b432700-1d34-11eb-96b0-288e512e6330.png)

**Comment by noklam** [comment]
@Optimox 

Yes I am running on the same machine with GTX 1080 Ti and more than enough RAM. I don't think Window would slow down that much normally. I clone this code from a Kaggle Kernel and it is using Pytorch 1.7.

Does the implementation of using some distributed training out of the box that may not be supported well on Window?

**Comment by Optimox** [comment]
There is no distributed training, we're not doing anything special.

What happens if you set the device to 'cpu' in linux ? If you have the same training time as in Windows I guess you are not really using  your GPU on Windows.

Can't really help much on this...

**Comment by noklam** [comment]
I am closing this issue as I found the problem seems to be i have a dataloader with num_worker>0 which has some adverse effect on Window rather than the model itself.

thanks for the help.
