### ISSUE TITLE
Using GridSearchCV

### ISSUE THREAD

**Issue by nclibz** [dreamquark-ai/tabnet#238]
## Feature request
First of, I want to say thank you for creating this PyTorch implementation of Tabnet. 
I have a small feature request: 
Is it possible to take batch_size, virtual_batch_size, drop_last and max_epochs as arguments during init instead of when calling fit? 

**What is the expected behavior?**
As per the sklearn documentation the GridSearchCV uses the inherited set_params method to change the specified parameters. However, this is currently not possible due to the attributes first being assigned when calling the fit method. 

**What is motivation or use case for adding/changing the behavior?**
This will make it possible to use to use  GridSearchCV or, in my case, skopt.BayesSearchCV,  to tune the above mentioned arguments as hyperparameters. 

**How should this be implemented in your opinion?**
Take the arguments at init instead of when calling fit. 

**Are you willing to work on this yourself?**
Willing, yes. Able, doubtful.

**Comment by Optimox** [comment]
Hi @nclibz,

Thanks for your message.

I was actually thinking of doing the opposite, i.e move some parameters from Tabnet and put them into the `fit` call (like lambda_sparse, verbose etc..). My idea is to leave only the architecture dependent parameters inside the TabNet class and put everything related to the training procedure in fit.

So this won't make things easier for GridSearchCV but will make things clearer IMO.

There is an easy way to use TabNet with GridSearchCV, you need to wrap it into a bigger class that will make the fit works. You can have a look here : https://github.com/dreamquark-ai/tabnet/issues/80#issuecomment-623079472
It's an old discussion so the TabNetTuner proposed here is not up to date, but the main idea is easy to understand and to adapt.

It might be interesting to put a TabNetTuner class inside the library though. Maybe this would be the best option.

**Comment by nclibz** [comment]
I completely agree that those parameters are more related to the fit method than the actual init. I just thought that the reason for making an sklearn implementation was to make it compatible with the rest of the sklearn ecosystem. 

I'll just make a thin wrapper as you suggested. Thank you for answering and sorry for starting a new thread for something that has already been brought up before.
