### ISSUE TITLE
pretraining

### ISSUE THREAD

**Issue by ZAJ0711** [dreamquark-ai/tabnet#247]
when i just pip install pytorch-tabnet and the version is pytorch-tabnet-2.0.1
the guide show that if i want to use the pretraining model i could 
from pytorch_tabnet.pretraining import TabNetPretrainer
but there is  not pytorch_tabnet.pretraining module

**Comment by Optimox** [comment]
Yes, the README shown on GitHub is the develop branch README.

You can pip install the develop branch with this line of code:

`!pip install  "git+https://github.com/dreamquark-ai/tabnet.git@develop#egg=pytorch_tabnet" --upgrade`

We will release soon the develop branch.

**Comment by Optimox** [comment]
the release of v3.0.0 is out, this should have solved your problem!
