### ISSUE TITLE
Single fit function that does pretraining + training

### ISSUE THREAD

**Issue by eduardocarvp** [dreamquark-ai/tabnet#250]
## Feature request

**What is the expected behavior?**

Use the same parameters as the classifier/regressor to create a PreTrainer and then train normally.  

**What is motivation or use case for adding/changing the behavior?**

It would mostly simplify benchmarks and avoid the code repetition on notebooks.

**How should this be implemented in your opinion?**

A `fit_with_unsupervised` function that belong to `TabModel` and that does all the job.

**Are you willing to work on this yourself?**

Yes

**Comment by Optimox** [comment]
@eduardocarvp I'm closing this as I'm not convinced at the moment. We might reopen if it feels more appropriate later.
