### ISSUE TITLE
Fix Typo

### ISSUE THREAD

**Issue by mei28** [dreamquark-ai/tabnet#254]
**Describe the bug**

I found some typos in docstring and alert.

Can I fix these typos and send pull request?

Hope to hear from you soon！ 

ex) 
![image](https://user-images.githubusercontent.com/51149822/102852634-05386d80-4462-11eb-894b-819b5bf382c1.png)

**What is the current behavior?**
N/A
**If the current behavior is a bug, please provide the steps to reproduce.**

N/A
**Expected behavior**

N/A
**Screenshots**

**Other relevant information:**
N/A
**Additional context**
N/A

**Comment by Optimox** [comment]
Hello @mei28,

Sure feel free to open a PR. Please could you name your commit something like `chore: docstring typos` ? If you see more typos don't hesitate to correct them! Thanks!
