### ISSUE TITLE
Cannot use all the cores when running training on CPU

### ISSUE THREAD

**Issue by nitinmnsn** [dreamquark-ai/tabnet#256]
**All the cores in CPU are not getting utilized.**

**Current behavior**
I have not touched the num_worker parameter since it seems to be for data loading purposes. My machine has 16 cores but only 8 seems to be busy at any time

**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**
All cores of my machine being utilized while training

**Screenshots**

**Other relevant information:**
poetry version:  
python version: 3.8
Operating System: ubuntu 18.04
Additional tools: 

**Additional context**

**Comment by Optimox** [comment]
Hello @nitinmnsn,

I don't think this is a pytorch-tabnet bug, we are using basic dataloaders from pytorch.

Sometimes pytorch is hard to optimize on CPU, maybe you can have a look at this: https://github.com/pytorch/pytorch/issues/9873

If you do find a way to use all the cpu cores at full speed please let us know.
