### ISSUE TITLE
Faster Tabular Dataloader

### ISSUE THREAD

**Issue by zhenpingfeng** [dreamquark-ai/tabnet#258]
## Feature request

**What is the expected behavior?**
Load data more faster than use `def __getitem__(self, index):
        x, y = self.x[index], self.y[index]
        return x, y`

**What is the motivation or use case for adding/changing the behavior?**
Fix the CPU to GPU data-loading bottleneck.

**How should this be implemented in your opinion?**
Already have an implemented.
https://github.com/hcarlens/pytorch-tabular/blob/master/fast_tensor_data_loader.py

**Are you willing to work on this yourself?**
No

**Comment by Optimox** [comment]
Thanks for pointing out this dataloading scheme, I'l make some tests to see how much it improves the training time! Did you make any experiment yourself?

**Comment by zhenpingfeng** [comment]
I didn't test with the Tabnet, but with others large models, it's indeed can speed up 10~20 times.

**Comment by Optimox** [comment]
@eduardocarvp any speed up in sight?

**Comment by tim5go** [comment]
@Optimox @eduardocarvp 
It seems like a very useful Feature Request to me too.
May I know what is the blocker?

**Comment by Optimox** [comment]
@tim5go the only blocker is that we never saw any speed up…

**Comment by zhenpingfeng** [comment]
cool, then I will close this issue.

**Comment by tim5go** [comment]
@Optimox 
Just curious, what is the size of the dataset being tested?
Is it possible that the size is too small so that we can't see the improvement?
