### ISSUE TITLE
'TabNetPretrainer' object has no attribute 'preds_mapper'

### ISSUE THREAD

**Issue by tmontana** [dreamquark-ai/tabnet#264]
**Describe the bug**
when running example pretraining_example.ipynb as-is I get the following error message when trying to save the model:
unsupervised_model.save_model('./test_pretrain')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-046c2a29fa3f> in <module>
----> 1 unsupervised_model.save_model('./test_pretrain')
      2 loaded_pretrain = TabNetPretrainer()
      3 loaded_pretrain.load_model('./test_pretrain.zip')

/anaconda/envs/tabnet_3/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py in save_model(self, path)
    364 
    365         class_attrs = {
--> 366             "preds_mapper": self.preds_mapper
    367         }
    368         saved_params["class_attrs"] = class_attrs

AttributeError: 'TabNetPretrainer' object has no attribute 'preds_mapper'

>

**What is the current behavior?**
see AttributeError above

**If the current behavior is a bug, please provide the steps to reproduce.**
just run the pre-train example notebook.  error occurs in cell 20.

-->

**Expected behavior**
Should allow me to save the model and continue with notebook execution

**Screenshots**

**Other relevant information:**
poetry version:  None
python version: 3.8
Operating System: Ubuntu 16.4
Additional tools: VM running on Azure ML

**Additional context**

**Comment by eduardocarvp** [comment]
Thanks @tmontana . That is probably related to https://github.com/dreamquark-ai/tabnet/pull/253. I must have forgotten to do the necessary modifications to the pretrainer. I'll have a look as soon as I can.

**Comment by tmontana** [comment]
Thanks!

**Comment by Optimox** [comment]
@eduardocarvp is the pretraining_example in the CI?

**Comment by eduardocarvp** [comment]
Actually no, @Optimox . I added the notebook to the CI [here](https://github.com/dreamquark-ai/tabnet/pull/267), let's see if it works.
