### ISSUE TITLE
Error loading saved model

### ISSUE THREAD

**Issue by casonatia** [dreamquark-ai/tabnet#265]
**Describe the bug**
Error when loading saved model  running this code from https://github.com/dreamquark-ai/tabnet/blob/develop/census_example.ipynb :
```
saving_path_name = "./tabnet_model_test_1"
saved_filepath = model.save_model(saving_path_name)
loaded_clf = TabNetClassifier()
loaded_clf.load_model(saved_filepath)
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-6a8b0b4d0367> in <module>()
     11 # define new model with basic parameters and load state dict weights
     12 loaded_clf = TabNetClassifier()
---> 13 loaded_clf.load_model(saved_filepath)

C:\Users\andrea\Anaconda3\envs\pippo\lib\site-packages\pytorch_tabnet\abstract_model.py in load_model(self, filepath)
    397                 with z.open("network.pt") as f:
    398                     try:
--> 399                         saved_state_dict = torch.load(f, map_location=self.device)
    400                     except io.UnsupportedOperation:
    401                         # In Python <3.7, the returned file object is not seekable (which at least

C:\Users\andrea\Anaconda3\envs\pippo\lib\site-packages\torch\serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    585             # reset back to the original position.
    586             orig_position = opened_file.tell()
--> 587             with _open_zipfile_reader(opened_file) as opened_zipfile:
    588                 if _is_torchscript_zip(opened_zipfile):
    589                     warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"

C:\Users\andrea\Anaconda3\envs\pippo\lib\site-packages\torch\serialization.py in __init__(self, name_or_buffer)
    240 class _open_zipfile_reader(_opener):
    241     def __init__(self, name_or_buffer) -> None:
--> 242         super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
    243 
    244 

C:\Users\andrea\Anaconda3\envs\pippo\lib\zipfile.py in seek(self, offset, whence)
   1023             # Position is before the current position. Reset the ZipExtFile
   1024 
-> 1025             self._fileobj.seek(self._orig_compress_start)
   1026             self._running_crc = self._orig_start_crc
   1027             self._compress_left = self._orig_compress_size

C:\Users\andrea\Anaconda3\envs\pippo\lib\zipfile.py in seek(self, offset, whence)
    702     def seek(self, offset, whence=0):
    703         with self._lock:
--> 704             if self.writing():
    705                 raise ValueError("Can't reposition in the ZIP file while "
    706                         "there is an open writing handle on it. "

AttributeError: '_SharedFile' object has no attribute 'writing'

**What is the current behavior?**
see AttributeError above

**If the current behavior is a bug, please provide the steps to reproduce.**
just run  https://github.com/dreamquark-ai/tabnet/blob/develop/census_example.ipynb

**Expected behavior**

Should allow me to load the model

**Screenshots**

**Other relevant information:**
poetry version:  
python version: 3.7
Operating System: Windows 10
Additional tools: Visual Studio Code

**Additional context**

**Comment by Optimox** [comment]
hello @casonatia,

The notebooks of the repo are running fine as they are used for the continuous integration, so pointing to the notebook to reproduce your bug is not enough.

It seems that it might be a read/write issue or it could be a problem with Windows system (this is not tested by the CI), I'm not sure how to help without more information. Could you try to produce a minimal reproducible code generating this error on your machine and then try to run it in a Colab or Kaggle environment and let us know if it solves the problem?

Thank you for reporting!

**Comment by eduardocarvp** [comment]
I have not tested and I do not know if this can help, but it looks like exactly the same problem and same python version: https://stackoverflow.com/questions/52855273/python3-code-uploading-to-s3-bucket-with-io-instead-of-string-io.

Apparently it is a bug with python 3.7.

**Comment by Optimox** [comment]
@casonatia feel free to reopen when you have more information to share.
