### ISSUE TITLE
Good example of tabnet on a regression problem

### ISSUE THREAD

**Issue by turmeric-blend** [dreamquark-ai/tabnet#268]
## Feature request

**What is the expected behavior?**
Example to reproduce results from the [tabnet paper](https://arxiv.org/pdf/1908.07442.pdf) on **Rossmann Store Sales**

**What is motivation or use case for adding/changing the behavior?**
The current [example](https://github.com/dreamquark-ai/tabnet/blob/develop/regression_example.ipynb) on regression is a bit confusing to me. The example predicts for "income level" which only has two options `<=50K` and `>50k`. Maybe I missed something, but I don't think this is a regression problem?

**How should this be implemented in your opinion?**
An example using Rossmann Store Sales

**Are you willing to work on this yourself?**
No, I am trying to learn tabnet on regression (so I think I lack the skills to do this currently), but need a good example to learn on that is why I am asking this :/

Thank you.

**Comment by Optimox** [comment]
Hi @turmeric-blend,

The regression example is a toy example, on how you can decide to treat a binary classification example as regression.
It's mostly to show the basics, you should be able to easily replace the dataset with any other one for regression and it should work with a few changes.

If you are looking for more examples on real datasets I would advise you to have a look on Kaggle notebooks:
- https://www.kaggle.com/optimo/tabnetregressor-2-0-train-infer (multiple output regression - still for binary classification tasks)
- https://www.kaggle.com/carlmcbrideellis/tabnet-a-very-simple-regression-example (traditional regression)
- https://www.kaggle.com/aeryss/tabular-playground-jan-2021-tabnet-baseline (traditional regression)

This should be enough to start using TabNetRegressor on any given dataset.

**Comment by turmeric-blend** [comment]
Hi @Optimox, I am new to kaggle. How do we download the dataset to test the code out?

**Comment by turmeric-blend** [comment]
Hi @Optimox I have a follow-up question. Since I am having trouble running this [notebook](https://www.kaggle.com/aeryss/tabular-playground-jan-2021-tabnet-baseline) (can't seem to install cuML), I want to know does tabnet **support** time series regression problems (for example predict for future energy demand, in this case, the input features would be past energy demand time series)?

The notebook seems to be the closest to a time series regression problem (out of the 3 links you gave) but it seems like there are preprocessing steps that change some columns to categorical and drops the original time series. However, I can't confirm this as I can't fully run the notebook to know what is the inputs to the tabnet regressor model.

**Comment by eduardocarvp** [comment]
Hi @turmeric-blend ,

TabNet does not support time series classification or regression. You can have a look [here](https://towardsdatascience.com/using-gradient-boosting-for-time-series-prediction-tasks-600fac66a5fc), for example, on how to adapt a time series problem to a classic regression algorithm like `XGBoostRegressor` or `TabNetRegressor`.

If you really need some specific algorithm for time series data I'd refer to [gluonTS](https://ts.gluon.ai/) or some similar library.

**Comment by Optimox** [comment]
To add a few words, best way to use a Kaggle Notebook is probably to fork it, you'll then be able to run it in your web browser within a docker container with all the libraries installed, or you can work in docker container yourself: https://github.com/Kaggle/docker-python (kaggle container is huge so not the best way).

About time series, TabNet is similar to XGBoost on this, you'll need to engineer explicit lag features in order to do time series forecasting. It's definitely doable and might be the good way to go BUT TabNet has nothing specific to time series like Temporal Convolutional Networks.

**Comment by turmeric-blend** [comment]
Thanks @Optimox @eduardocarvp for the suggestions! I will look into it :)
