### ISSUE TITLE
How to calculate the number of learning parameters in TabNet?

### ISSUE THREAD

**Issue by unnir** [dreamquark-ai/tabnet#270]
Hi, 

sorry, could not join the slack, the link is broken or something. 

I have a very simple question how to calculate the number of learning parameters in TabNet? 

Thank you!

## Feature request

**What is the expected behavior?**

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by Optimox** [comment]
The slack link should be alright, it expires in a thousand years ^^

In order to know the number or parameters you could do (as answered here : https://stackoverflow.com/questions/49201236/check-the-total-number-of-parameters-in-a-pytorch-model/62764464#62764464 )

```
clf = TabNetClassifier()
clf.fit(X, Y)
num_params = sum(dict((p.data_ptr(), p.numel()) for p in clf.network.parameters()).values())
print(num_params)
```

**Comment by unnir** [comment]
Thank you!
