### ISSUE TITLE
Model weights not reset when calling fit()

### ISSUE THREAD

**Issue by behoward** [dreamquark-ai/tabnet#271]
I set up a 5-fold cross validation loop to test the TabNet classifier in comparison to other sklearn classifiers.  TabNet blew them all away. Unfortunately, it turned out that the reason was because TabNet, unlike other sklearn classifiers, does not overwrite weights on each new call to fit() so that, in effect, the held out test fold was previously used as part of a prior training set.. I solved the problem by instantiating a new TabNetClassifier instance for each fold, but this was unexpected behavior.

see sklearn conventions for refitting and updating: https://scikit-learn.org/stable/tutorial/basic/tutorial.html#refitting-and-updating-parameters

**Comment by eduardocarvp** [comment]
Thanks, @behoward . Indeed the sklearn convention is pretty clear on this, but I'm not sure it is the best choice in our case. The training process is much longer for TabNet compared to most sklearn classifiers and I can see cases in which the user would just like to train for longer without having to start everything from the beginning again.
What do you think about this, @Optimox ?

**Comment by Optimox** [comment]
Hello @behoward,

Thanks for your feedback.

Indeed pytorch-tabnet is scikit-friendly and not scikit-ruled. This behavior was a choice we made because with deep learning models it is very common to do re-training, fine-tuning or things like 'life-long learning'.

I would be ok to find a better way to allow this, but the current behavior seems simple and intuitive to me. We should definitely make this clearer in the README though.

Instanciating inside the CV loop looks like the right think to do, I hope you did not lose too much time on this issue.

I would be very interested to know more about the results of your (fair) comparison, could you share some?

**Comment by behoward** [comment]
I can understand your point, and the current behavior makes a lot of sense in certain scenarios. On the other hand, implementing a scikit-learn interface but not following the 'contract' of that interface seems very likely to cause problems.  Fortunately, there are some mechanisms in scikit-learn for supporting incremental learning, etc.  For example, perhaps you could provide a "warm-start" parameter and/or implement the "partial_fit" interface:

https://datascience.stackexchange.com/questions/68599/incremental-learning-with-sklearn-warm-start-partial-fit-fit
https://scikit-learn.org/stable/computing/scaling_strategies.html?highlight=incremental%20learning#incremental-learning
https://scikit-learn.org/stable/developers/develop.html?highlight=warm_start#fitting

Anyway, thanks for your work to implement tabnet according to an easy-to-use way and familiar interface. So far, I am just learning how to use tabnet, so I don't have any interesting results to share, other than in the end it was comparable to other standard classification methods.  It is a small dataset though, so probably deep learning is not needed anyway.

**Comment by Optimox** [comment]
Maybe a warm-start would be the go to solution, I'll think about it thanks!

**Comment by albert-ying** [comment]
> I set up a 5-fold cross validation loop to test the TabNet classifier in comparison to other sklearn classifiers. TabNet blew them all away. Unfortunately, it turned out that the reason was because TabNet, unlike other sklearn classifiers, does not overwrite weights on each new call to fit() so that, in effect, the held out test fold was previously used as part of a prior training set.. I solved the problem by instantiating a new TabNetClassifier instance for each fold, but this was unexpected behavior.
> 
> see sklearn conventions for refitting and updating: https://scikit-learn.org/stable/tutorial/basic/tutorial.html#refitting-and-updating-parameters

Hi! I would like to avoid this behavior in my code. Just wondering whether "instantiating a new TabNetClassifier instance" means doing this? Or do I have to change the variable name as well?

```
for i in range(1, 10):
  tn = TabNetRegressor()
  tn.fit(...) # fit on training set i
# then save the model
```

**Comment by behoward** [comment]
> Hi! I would like to avoid this behavior in my code. Just wondering whether "instantiating a new TabNetClassifier instance" means doing this? Or do I have to change the variable name as well?

Your code looks like it would be ok. I.e. it should be ok to re-use the variable name as long as a new object gets created.
