### ISSUE TITLE
Error while loading saved model and predict step

### ISSUE THREAD

**Issue by puneethmishra** [dreamquark-ai/tabnet#273]
**Describe the bug**
I had saved the model using the below steps 
saving_path_name = "./tabnet_model_test1"
saved_filepath = clf.save_model(saving_path_name) in the training script

The entire coding was done in an azure notebook using a gpu

**What is the current behavior?**
In the deployment script , i load the model using the below commands:
from pytorch_tabnet.tab_model import TabNetClassifier
DEVICE_Serving = "./tabnet_model_test1.zip"
clf2=TabNetClassifier()
clf2.load_model(DEVICE_Serving)

**If the current behavior is a bug, please provide the steps to reproduce.**

Error i'm getting when i use the command:
clf2.predict(Inference_Data):

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2896             try:
-> 2897                 return self._engine.get_loc(key)
   2898             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-112-782c0b5a63aa> in <module>
----> 1 clf2.predict(Data)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pytorch_tabnet/abstract_model.py in predict(self, X)
    264 
    265         results = []
--> 266         for batch_nb, data in enumerate(dataloader):
    267             data = data.to(self.device).float()
    268             output, M_loss = self.network(data)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    361 
    362     def __next__(self):
--> 363         data = self._next_data()
    364         self._num_yielded += 1
    365         if self._dataset_kind == _DatasetKind.Iterable and \

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    401     def _next_data(self):
    402         index = self._next_index()  # may raise StopIteration
--> 403         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    404         if self._pin_memory:
    405             data = _utils.pin_memory.pin_memory(data)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pytorch_tabnet/utils.py in __getitem__(self, index)
     49 
     50     def __getitem__(self, index):
---> 51         x = self.x[index]
     52         return x
     53 

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2993             if self.columns.nlevels > 1:
   2994                 return self._getitem_multilevel(key)
-> 2995             indexer = self.columns.get_loc(key)
   2996             if is_integer(indexer):
   2997                 indexer = [indexer]

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2897                 return self._engine.get_loc(key)
   2898             except KeyError:
-> 2899                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2900         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2901         if indexer.ndim > 1 or indexer.size > 1:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0

**Expected behavior**

I also tried using the pickle method to save and load the model:
while saving the model in training script used :
import pickle 
with open("./TABNET_DEVICE_Failure.pkl","wb") as model_file:
    pickle.dump(clf, model_file)

In deployment script used the below command to load the model:
import pickle 
  
with open("./TABNET_DEVICE_Failure.pkl","rb") as model_file:
    new_clf = pickle.load(model_file)

new_clf.predict(Data) 
Error i get:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-114-2c946cfd6c09> in <module>
----> 1 new_clf.predict(Data)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pytorch_tabnet/abstract_model.py in predict(self, X)
    256             Predictions of the regression problem
    257         """
--> 258         self.network.eval()
    259         dataloader = DataLoader(
    260             PredictDataset(X),

AttributeError: 'TabNetClassifier' object has no attribute 'network'

**Screenshots**

**Other relevant information:**
poetry version:  
python version:  3.6
Operating System: Unix
Additional tools: Azure  Notebook

**Additional context**

**Comment by Optimox** [comment]
Hmm, what is inside `Data` when you call `clf2.predict(Data)` ? It looks like the given prediction data set is not in a correct format, it should be a numpy matrix.

Could you check that and let me know?

**Comment by puneethmishra** [comment]
It is a pandas dataframe, do i need to convert it into a numpy matrix?

**Comment by Optimox** [comment]
yes you should make sure that your columns are in the same order as when you trained your model and then do
`X_predict = my_df[ordered_features_list].values`

**Comment by puneethmishra** [comment]
Hi ,

After changing the order and changing into a numpy array getting the below error:
--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-125-dd5fa463c42d> in <module>
      1 Data1=Data.to_numpy()
      2 
----> 3 clf2.predict(Data1)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pytorch_tabnet/abstract_model.py in predict(self, X)
    264 
    265         results = []
--> 266         for batch_nb, data in enumerate(dataloader):
    267             data = data.to(self.device).float()
    268             output, M_loss = self.network(data)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    361 
    362     def __next__(self):
--> 363         data = self._next_data()
    364         self._num_yielded += 1
    365         if self._dataset_kind == _DatasetKind.Iterable and \

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    401     def _next_data(self):
    402         index = self._next_index()  # may raise StopIteration
--> 403         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    404         if self._pin_memory:
    405             data = _utils.pin_memory.pin_memory(data)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     45         else:
     46             data = self.dataset[possibly_batched_index]
---> 47         return self.collate_fn(data)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
     60             # array of string classes and object
     61             if np_str_obj_array_pattern.search(elem.dtype.str) is not None:
---> 62                 raise TypeError(default_collate_err_msg_format.format(elem.dtype))
     63 
     64             return default_collate([torch.as_tensor(b) for b in batch])

TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found object

Do i need to also carry out the pre-processing steps , that i was doing with the training data?

**Comment by puneethmishra** [comment]
Thanks for all your help , had to carry out the pre-processing steps on Inference data and then it worked out.

**Comment by Optimox** [comment]
Great! I'm closing this then, feel free to reopen if needed.
