### ISSUE TITLE
hello! How to Parameters Tunning in Tabnet?

### ISSUE THREAD

**Issue by learningelectric** [dreamquark-ai/tabnet#275]
Dear sir
I am new to use Tabnet , Specially I  donot clearly know 'cat_dims,  cat_emb_dim,  cat_idxs' . I can not understand theory of three parameters , And I want to know how useful to make parameters tunning.  I hope you can give me some suggestions about this question.
Thank you very much!

**Comment by Optimox** [comment]
Those parameters are related to embedding dimensions for categorical features.

If you are not familiar with this concept I'll suggest you to search on Google, links like this one should be useful https://towardsdatascience.com/deep-embeddings-for-categorical-variables-cat2vec-b05c8ab63ac0 (havent read it but should be alright).

To sum up:
- `cat_idxs` : a list of int, this simply represents what columns index should be considered as categorical features and embed them.
- `cat_dims`: a list of int, this is the number of categories each categorical features has (same order as `cat_idxs`), each category will have its own embedding representation
- `cat_emb_dim` : can be either a single int or a list of int, this represents the dimension you want to use for each categorical column in the embedding space.

Here's a recent notebook showing how you can use embeddings for categorical features : https://www.kaggle.com/optimo/tabnet-baseline

**Comment by learningelectric** [comment]
ok, Thank you very much ! I will try it.

**Comment by Optimox** [comment]
feel free to reopen if needed!
