### ISSUE TITLE
RuntimeError: running_mean should contain 136 elements not 135

### ISSUE THREAD

**Issue by Vickyilango** [dreamquark-ai/tabnet#276]
On doing clt.predict getting this 

RuntimeError: running_mean should contain 136 elements not 135

**Comment by eduardocarvp** [comment]
Hi @Vickyilango , could you give more details on what is the code you are executing to get this error, please?

**Comment by Vickyilango** [comment]
Sorry. My bad . The test shapes were mismatching after a step in my preprocessing. Thanks for the fast response
