### ISSUE TITLE
Exception: data must be 1-dimensional when creating network on tabular dataset.

### ISSUE THREAD

**Issue by 9849842** [dreamquark-ai/tabnet#280]
**What is the current behavior?**

When training classifier, I get an error saying data must be 1 dimensional

**If the current behavior is a bug, please provide the steps to reproduce.**
import numpy as np
from pytorch_tabnet.tab_model import TabNetClassifier

xTrain = np.random.rand(10,10)
yTrain = np.random.randint(0,2,size=(10,1))

clf = TabNetClassifier() 

clf.fit(
    X_train = xTrain,
    y_train = yTrain,
    eval_set=[(xTrain, yTrain)],
)
Device used : cuda
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-8-1b61cbf48bc1> in <module>
      8 clf = TabNetClassifier()  #TabNetRegressor()
      9 
---> 10 clf.fit(
     11     X_train = xTrain,
     12     y_train = yTrain,

~/.local/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py in fit(self, X_train, y_train, eval_set, eval_name, eval_metric, loss_fn, weights, max_epochs, patience, batch_size, virtual_batch_size, num_workers, drop_last, callbacks, pin_memory, from_unsupervised)
    183         check_array(X_train)
    184 
--> 185         self.update_fit_params(
    186             X_train,
    187             y_train,

~/.local/lib/python3.8/site-packages/pytorch_tabnet/tab_model.py in update_fit_params(self, X_train, y_train, eval_set, weights)
     50         weights,
     51     ):
---> 52         output_dim, train_labels = infer_output_dim(y_train)
     53         for X, y in eval_set:
     54             check_output_dim(train_labels, y)

~/.local/lib/python3.8/site-packages/pytorch_tabnet/multiclass_utils.py in infer_output_dim(y_train)
    370         Sorted list of initial classes
    371     """
--> 372     check_unique_type(y_train)
    373     train_labels = unique_labels(y_train)
    374     output_dim = len(train_labels)

~/.local/lib/python3.8/site-packages/pytorch_tabnet/multiclass_utils.py in check_unique_type(y)
    347 
    348 def check_unique_type(y):
--> 349     target_types = pd.Series(y).map(type).unique()
    350     if len(target_types) != 1:
    351         raise TypeError(

/opt/conda/lib/python3.8/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    325                     data = data.copy()
    326             else:
--> 327                 data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
    328 
    329                 data = SingleBlockManager.from_array(data, index)

/opt/conda/lib/python3.8/site-packages/pandas/core/construction.py in sanitize_array(data, index, dtype, copy, raise_cast_failure)
    494     elif subarr.ndim > 1:
    495         if isinstance(data, np.ndarray):
--> 496             raise Exception("Data must be 1-dimensional")
    497         else:
    498             subarr = com.asarray_tuplesafe(data, dtype=dtype)

Exception: Data must be 1-dimensional

**Expected behavior**

Model should train on the tabular dataset.

**Screenshots**

**Other relevant information:**
poetry version:  1.1.5
python version: 3.7
Operating System: ubuntu 18.04
Additional tools:

**Additional context**

**Comment by Optimox** [comment]
Classification must be done with LabelEncoded targets, not one hot encoded targets. So as the error message says, it must be 1D.

Apply label encoding to your targets and things should work just fine.

**Comment by 9849842** [comment]
Even adding the label encoding line, it still happens:
import numpy as np
from pytorch_tabnet.tab_model import TabNetClassifier
from sklearn.preprocessing import LabelEncoder

xTrain = np.random.rand(10,10)
yTrain = np.random.randint(0,2,size=(10,1))
yTrain = LabelEncoder().fit_transform(np.ravel(yTrain))

clf = TabNetClassifier()

clf.fit(
X_train = xTrain,
y_train = yTrain,
eval_set=[(xTrain, yTrain)],
)

**Comment by Optimox** [comment]
![dummy_code_ok](https://user-images.githubusercontent.com/12525461/114238737-69396000-9985-11eb-8c14-1b89c3669b5e.png)

your code runs just ok on my machine

**Comment by 9849842** [comment]
When I use my actual dataset it doesnt work... and I am checking with this:

In: len(pd.Series(yTrain).map(type).unique())
Out: 1

**Comment by 9849842** [comment]
Its because I never fixed yTest... damnit.
