### ISSUE TITLE
Raise an error if only `cat_idxs` is given

### ISSUE THREAD

**Issue by Optimox** [dreamquark-ai/tabnet#285]
## Feature request
When reading this : https://www.kaggle.com/soerendip/rossmann-with-tabnet-pytorch/
I think it's misleading to be able to give only cat_idxs, get no error message while the rest of the needed info is missing

**What is the expected behavior?**
Simply raise an error if all the necessary info is not here.

**What is motivation or use case for adding/changing the behavior?**
Avoid misuse of the library 

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by eduardocarvp** [comment]
Hey @Optimox , that is truly a complete misleading behavior. I have created a pull request raising an error inside the `EmbeddingGenerator` to handle the case where one argument is present while the other is not and the case where the lists have different lengths.
