### ISSUE TITLE
Does Tabnet could do gridsearchcv or random search ,pipeline search

### ISSUE THREAD

**Issue by tanpanfeng** [dreamquark-ai/tabnet#288]
## Feature request

**What is the expected behavior?**
Tabnet could do gridsearchcv or random search  ,pipeline search to find better better parameters for the test 
Could give some suggest parameters to improve the model trained. Such like Approaching (Almost) Any Machine Learning Problem Book suggestion
![image](https://user-images.githubusercontent.com/80340966/116111339-23043080-a6e9-11eb-8bda-d367a6ea820e.png)

**What is motivation or use case for adding/changing the behavior?**

Because doing a tabnet with GPU more than 30 minutes one time

**How should this be implemented in your opinion?**
If there are some example is better

**Are you willing to work on this yourself?**
No

**Comment by eduardocarvp** [comment]
Hello @tanpanfeng ,

I'm not sure I understand what you mean as expected behavior. Do you mean using `GridSearchCV` or `RandomizedSearchCV` from `sklearn` by default or something different?

**Comment by tanpanfeng** [comment]
> Hello @tanpanfeng ,
> 
> I'm not sure I understand what you mean as expected behavior. Do you mean using `GridSearchCV` or `RandomizedSearchCV` from `sklearn` by default or something different?

Yes,you could say it again!

**Comment by eduardocarvp** [comment]
On the original paper https://arxiv.org/pdf/1908.07442.pdf, under the section "Self-supervised learning on Forest Cover Type Experiment hyperparameters", page 9,  you can find the hyperparameters used by the authors.

I might be wrong, but I did not find suggested hyperparameters on the xgboost package itself. Anyways, do you think that if we show the paper suggested values on our README that could be useful?

**Comment by tanpanfeng** [comment]
> On the original paper https://arxiv.org/pdf/1908.07442.pdf, under the section "Self-supervised learning on Forest Cover Type Experiment hyperparameters", page 9, you can find the hyperparameters used by the authors.
> 
> I might be wrong, but I did not find suggested hyperparameters on the xgboost package itself. Anyways, do you think that if we show the paper suggested values on our README that could be useful?

Thank you so much for your help

**Comment by eduardocarvp** [comment]
Closing this issue, feel free to open again if needed.
