### ISSUE TITLE
Error when saving model

### ISSUE THREAD

**Issue by Shigan-Liu** [dreamquark-ai/tabnet#299]
Hi, I attempted to use `TabNetRegressor` to fit my tabular data. It is defined as followings:

```python
reg = TabNetRegressor(seed=SEED, n_d=n_d, n_a=n_a, n_steps=n_steps, gamma=gamma,
                      n_independent=n_independent, n_shared=n_shared,
                      momentum=momentum, saving_path='./models/')
```

Parameters like `SEED`, `n_d`, `n_a` and etc. have been pre-defined. However, it returns

```
Traceback (most recent call last):
  File "1.case02.TabNet.seed_1024.py", line 115, in <module>
    reg = TabNetRegressor(seed=SEED, n_d=n_d, n_a=n_a, n_steps=n_steps, gamma=gamma,
TypeError: __init__() got an unexpected keyword argument 'saving_path'
```

I read the codes, `abstract_model.py` and `tab_model.py`, but neither parameter `saving_path` nor `model_name` was found which is introduced in README. 

I'm wondering whether the way to save the model is wrong. 

Thanks!

**Comment by Optimox** [comment]
Hello @Shigan-Liu, 

Yes you are right the documentation is not up to date, please refer to the notebooks example (this one for example : https://github.com/dreamquark-ai/tabnet/blob/develop/census_example.ipynb) to see how to save and load models.

**Comment by Shigan-Liu** [comment]
Hello @Optimox ,

Thank you for the reply! It works and I'll close this issue.
