### ISSUE TITLE
Can not save the model.

### ISSUE THREAD

**Issue by Goldgaruda** [dreamquark-ai/tabnet#300]
**Describe the bug**

**What is the current behavior?**
Can not save the model
**If the current behavior is a bug, please provide the steps to reproduce.**

4
**Expected behavior**

**Screenshots**

TypeError                                 Traceback (most recent call last)
<ipython-input-208-63fcdc628610> in <module>
      1 # save tabnet model
      2 saving_path_name = "./tabnet_model_test_1"
----> 3 saved_filepath = clf.save_model(saving_path_name)

E:\aws\pytorch_tabnet\abstract_model.py in save_model(self, path)
    373         # Save models params
    374         with open(Path(path).joinpath("model_params.json"), "w", encoding="utf8") as f:
--> 375             json.dump(saved_params, f, cls=ComplexEncoder)
    376 
    377         # Save state_dict

~\anaconda3\envs\py37\lib\json\__init__.py in dump(obj, fp, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    177     # could accelerate with writelines in some versions of Python, at
    178     # a debuggability cost
--> 179     for chunk in iterable:
    180         fp.write(chunk)
    181 

~\anaconda3\envs\py37\lib\json\encoder.py in _iterencode(o, _current_indent_level)
    429             yield from _iterencode_list(o, _current_indent_level)
    430         elif isinstance(o, dict):
--> 431             yield from _iterencode_dict(o, _current_indent_level)
    432         else:
    433             if markers is not None:

~\anaconda3\envs\py37\lib\json\encoder.py in _iterencode_dict(dct, _current_indent_level)
    403                 else:
    404                     chunks = _iterencode(value, _current_indent_level)
--> 405                 yield from chunks
    406         if newline_indent is not None:
    407             _current_indent_level -= 1

~\anaconda3\envs\py37\lib\json\encoder.py in _iterencode_dict(dct, _current_indent_level)
    403                 else:
    404                     chunks = _iterencode(value, _current_indent_level)
--> 405                 yield from chunks
    406         if newline_indent is not None:
    407             _current_indent_level -= 1

~\anaconda3\envs\py37\lib\json\encoder.py in _iterencode_dict(dct, _current_indent_level)
    403                 else:
    404                     chunks = _iterencode(value, _current_indent_level)
--> 405                 yield from chunks
    406         if newline_indent is not None:
    407             _current_indent_level -= 1

~\anaconda3\envs\py37\lib\json\encoder.py in _iterencode(o, _current_indent_level)
    436                     raise ValueError("Circular reference detected")
    437                 markers[markerid] = o
--> 438             o = _default(o)
    439             yield from _iterencode(o, _current_indent_level)
    440             if markers is not None:

E:\aws\pytorch_tabnet\utils.py in default(self, obj)
    337             return int(obj)
    338         # Let the base class default method raise the TypeError
--> 339         return json.JSONEncoder.default(self, obj)

~\anaconda3\envs\py37\lib\json\encoder.py in default(self, o)
    177 
    178         """
--> 179         raise TypeError(f'Object of type {o.__class__.__name__} '
    180                         f'is not JSON serializable')
    181 

TypeError: Object of type int32 is not JSON serializable
**Other relevant information:**
poetry version:  
python version: 3.7
Operating System: Windows
Additional tools:

**Additional context**

After training, I want to save the model. But an error message appears.

json.dump(saved_params, f, cls=ComplexEncoder)
 f'is not JSON serializable'

**Comment by Optimox** [comment]
I don't know, @eduardocarvp any idea?

**Comment by Hartorn** [comment]
@Optimox Looks like a numpy int32 is arriving to the save model function, and not a python int32.
Basically, `json.dumps` is not able to serialize it, it would be better to pass native python int.

@Goldgaruda could you provide the code where you init you parameters ?
Are you giving integers or list of integers at the input of the model ? If yes, could you check if they are numpy integer ?
(it's quite easy to transform them, using `tolist()` for a numpy array or `.item()` for a scalar.

**Comment by Optimox** [comment]
@Goldgaruda any news about your problem ?

**Comment by Optimox** [comment]
Closing this, please reopen when you have more information to share.
