### ISSUE TITLE
Is it ok to use more than two shared and independent blocks ?

### ISSUE THREAD

**Issue by MustaphaBM** [dreamquark-ai/tabnet#306]
It is just a begginer question. Is it ok to use n_shared between [1,4] and n_independent between [1,4] ?

**Comment by eduardocarvp** [comment]
Hi @MustaphaBM ,

On the original paper they use `n_shared=n_independent=2` on all their experiments. On the Ablation Studies section there is a small comment on that: "Replacing the feature transformer block with a simpler alternative, such as a single shared layer, can still give strong performance while yielding a very compact model architecture".

I guess you the range you are trying is ok, I suggest you try out come grid search on these values to see which one suits best your specific problem.

**Comment by MustaphaBM** [comment]
@eduardocarvp Thank you for this clear response.

**Comment by eduardocarvp** [comment]
No worries! I'm closing this issue, feel free to open a new one or ask on our slack chat if you have any further questions ;)
