### ISSUE TITLE
Not calling set_params is making model crash (no batch size)

### ISSUE THREAD

**Issue by Hartorn** [dreamquark-ai/tabnet#31]
**Describe the bug**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**

**Screenshots**

**Other relevant information:**
poetry version:  
python version: 
Operating System: 
Additional tools:

**Additional context**

**Comment by Optimox** [comment]
The current implementation requires parameters to be explicitely given, with #41 this should be solved.

**Comment by Optimox** [comment]
Closing this since #41 solves the problem
