### ISSUE TITLE
Tabnet is not detecting gpu

### ISSUE THREAD

**Issue by sparcycram** [dreamquark-ai/tabnet#310]
**Describe the bug**
Tabnet doesn't recognise my gpu defaults to cpu

I am using the following line
device_name='auto'
Tabnet keeps using cpu. I have a gpu installed and it is recognised and runs when using xgboost gpu_hist setting
**What is the current behavior?**
defaults to cpu
**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**

**Screenshots**

Device used : cpu
epoch 0  | loss: 0.13862 | val_0_rmse: 0.22663 |  0:03:00s
epoch 1  | loss: 0.0516  | val_0_rmse: 0.22589 |  0:06:14s
epoch 2  | loss: 0.05111 | val_0_rmse: 0.22447 |  0:09:22s
**Other relevant information:**
poetry version:  
python version: 3.8 spyder 4.2.5
Operating System: Windows 10
Additional tools:

**Additional context**

The same problem is happening on my colleagues PC

**Comment by eduardocarvp** [comment]
Hey @sparcycram ,

A bit more information, could you tell us what `torch.cuda.is_available()` outputs on the environment you are trying to run TabNet?

**Comment by sparcycram** [comment]
torch.cuda.is_available()
Out[12]: False

torch.zeros(1).cuda()
Traceback (most recent call last):

  File "<ipython-input-13-0904fac96cba>", line 1, in <module>
    torch.zeros(1).cuda()

  File "C:\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 166, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")

AssertionError: Torch not compiled with CUDA enabled


Looks like pytorch has been installed without CUDA support. Will try to rectify and revert

Thanks

**Comment by eduardocarvp** [comment]
Thanks for the outputs. Yes, apparently a problem with the PyTorch installation, like you said.
I'm closing the issue, feel free to open it again if you still have the same problem. Note that this is the only check that is made by tabnet: https://github.com/dreamquark-ai/tabnet/blob/b6e1ebaf694f37ad40a6ba525aa016fd3cec15da/pytorch_tabnet/utils.py#L308

 Cheers!

**Comment by sparcycram** [comment]
got it working needed to use cuda 10.2. Its much faster it says Device used : cuda but there is nothing in task manager on gpu, it is using gpu memory?
![image](https://user-images.githubusercontent.com/16734225/127923246-b987b651-8844-4978-973d-1180f2ed3209.png)

Any thoughts?
