### ISSUE TITLE
error with userdefine Loss

### ISSUE THREAD

**Issue by graceyangfan** [dreamquark-ai/tabnet#312]
**Describe the bug**
When using a user_define Loss for loss_fn 

```
class RMSELoss(torch.nn.Module):
    def __init__(self):
        super(RMSELoss,self).__init__()
    def forward(self,x,y):
        criterion = nn.MSELoss()
        eps = 1e-6
        loss = torch.sqrt(criterion(x, y) + eps)
        return loss
    clf = TabNetRegressor(**tabnet_params)

    # tabnet training

    clf.fit(
        X_train=X_train, y_train=y_train,
        eval_set=[(X_train, y_train), (X_valid, y_valid)],
        eval_name=['train', 'valid'],
        eval_metric=[RMSPE],
        max_epochs=max_epochs,
        patience=10,
        batch_size=1024*2, virtual_batch_size=128*2,
        num_workers=4,
        drop_last=False,
        weights =  y_weight ,
        loss_fn=RMSELoss()
    )
```
**What is the current behavior?**
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor []], which is output 0 of SqrtBackward, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**

**Screenshots**

**Other relevant information:**
poetry version:  3.1.1
python version:  python 3.8 
Operating System:  Linux 
Additional tools:

**Additional context**

**Comment by eduardocarvp** [comment]
Hello @graceyangfan ,

Looking at your code, your `clf` should be outside the `RMSELoss`, right?
Unless I'm mistaken, you don't think you need to create a new class. If you are using only torch operations, a function should be enough. Something like:

```
def myLoss(outputs, labels):
    # torch operations only
    return scalar
```

But I'm not sure why your example is not working, defining a class is also possible. I'd have to test it later to see where is the error.

**Comment by graceyangfan** [comment]
@eduardocarvp  yes,the clf is outside of the Loss,during my test,the code work well with pytorch's nn.Loss such as nn.MSELoss(),nn.L1Loss().But when  I change it to the RMSELoss,I meet the error

**Comment by eduardocarvp** [comment]
Don't know if you've already stumbled upon it, but this could be useful: https://github.com/NVlabs/FUNIT/issues/23.

**Comment by graceyangfan** [comment]
@eduardocarvp  Still working on it,it seem that it's a inplace operation falut,which is add to check recently for new version of pytorch,I will test my code

**Comment by Optimox** [comment]
@graceyangfan any news on this topic?

**Comment by graceyangfan** [comment]
no, I only try to rewrite TabNet in pytorch,and it works fine

**Comment by Optimox** [comment]
@graceyangfan what do you mean rewrite TabNet in pytorch ? pytorch-tabnet? :)
can we close this issue?

**Comment by graceyangfan** [comment]
@Optimox  close it,I have no idea why the usedefined loss can not work,I have to write my own version
