### ISSUE TITLE
Restore best weights after early stopping

### ISSUE THREAD

**Issue by soerendip** [dreamquark-ai/tabnet#317]
Hi,

I wonder what is the best way to restore the weights of the best iteration after early stopping? 

As an example, let's say the best epoch was 42 and patience was set to 10. So at epoch 52 the model stops, but the weights are now very different from epoch 42. Can I use standard pytorch callbacks for this?

**Comment by Optimox** [comment]
Hello, 
As written at the end of training in the printing logs, best weights are automatically used when setting a patience > 0.
So the library is automatically doing this, and you do not need to worry about it.

**Comment by soerendip** [comment]
Oh, great! For some reason the final performance seemed worse than the one of the best iteration.
