### ISSUE TITLE
Get parameters from saved model

### ISSUE THREAD

**Issue by jonimatix** [dreamquark-ai/tabnet#319]
Hi,

Is it possible to get the parameters used to train a saved model?

Thanks for your help

**Comment by Optimox** [comment]
Hi,

Yes, when you save a model it creates a zip file, inside this zip file you have a file named `model_params.json` which contains all necessary parameters to use the model for inference under a key named "init_params".

Or you can also see the parameters directly from your loaded model, by accessing the representation string `print(clf.__repr__)`

**Comment by jonimatix** [comment]
Thank you so much for your response
