### ISSUE TITLE
Question:  TabNet don't use the GPU, what I missed?

### ISSUE THREAD

**Issue by JRichetti** [dreamquark-ai/tabnet#321]
Hi folks,

When running tabnet, it doesn't use the GPU.
```
import torch
from pytorch_tabnet.tab_model import TabNetRegressor

print(torch.cuda.is_available())
...
```
This results in:

```
False
Device used : cpu
epoch 0  | loss: 3.02046 | val_0_rmsle: 1.10364 | val_0_mae: 9.47674 | val_0_rmse: 9.56173 | val_0_mse: 91.42676|  0:00:05s
epoch 1  | loss: 2.41663 | val_0_rmsle: 0.06228 | val_0_mae: 1.1556  | val_0_rmse: 1.40518 | val_0_mse: 1.97454 |  0:00:11s
epoch 2  | loss: 2.29922 | val_0_rmsle: 0.07031 | val_0_mae: 1.27784 | val_0_rmse: 1.50558 | val_0_mse: 2.26678 |  0:00:17s
```

I've used `pip install pytorch-tabnet`  and have loaded cuda/11.1 on my conda env.
Running on Linux

What am I doing wrong?
I'm relatively new to DL and could have missed something basic, so please be patient. 
Thanks!

**Comment by Optimox** [comment]
You need to follow a tutorial on how to install pytorch with your gpu.

`torch.cuda.is_available()` needs to be `True` : here is the installation page for pytorch https://pytorch.org/

**Comment by JRichetti** [comment]
Thanks for the pointer, but I do have it installed and when I load from the terminal this is what we get:
```
Python 3.9.6 (default, Aug 18 2021, 19:38:01)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
```
but when submiting the job I'm getting 'False' that is why I posted the question. I'll follow with my organisation HPC help as well. I was wondering if there was a 'switch' or something that I was missing. Anyway, any thoughts on this?

**Comment by eduardocarvp** [comment]
No worries @JRichetti , thank you for letting us know you found the problem!
I'm closing this one, feel free to open a new issue if you have any further questions ;)
