### ISSUE TITLE
plot_roc_curve() complains that TabNetClassifier is not a classifier

### ISSUE THREAD

**Issue by tddpirate** [dreamquark-ai/tabnet#322]
After running a fit on TabNetClassifier, I want to plot the ROC curve.
However, when running sklearn.metrics.plot_roc_curve, it does not create the plot. 

Instead of the plot, it throws the following exception:

ValueError: TabNetClassifier should be a binary classifier

I found from help(TabNetClassifier) that it does not have the sklearn.base.ClassiferMixin as one of its base classes.

**What is the current behavior?**
plot_roc_curve(tabnetclassifier, ...) does not create a ROC plot. Instead of this, it throws the exception:

ValueError: TabNetClassifier should be a binary classifier

**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**

plot_roc_curve() should recognize TabNetClassifier as a binary classifier.

**Screenshots**

**Other relevant information:**
poetry version:  ???
python version: 3.8.2
jupyter==1.0.0
jupyter-client==7.0.1
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
pytorch-tabnet==3.1.1
Operating System: Linux Debian 10.10 (Buster)
Additional tools: Jupyter

**Additional context**

**Comment by Optimox** [comment]
Hello,

Yes pytorch-tabnet is definitely not 100% scikit compatible.

You may try plotting the roc "by hand" using scikit : https://scikit-learn.org/stable/auto_examples/model_selection/plot_roc.html

**Comment by Optimox** [comment]
I'm closing this, feel free to reopen if you have more information or proposition on the subject.
