### ISSUE TITLE
Order of feature importances

### ISSUE THREAD

**Issue by furkanmtorun** [dreamquark-ai/tabnet#324]
**Describe the bug / The question**
What is the order of the feature importance? 

a) Order of the input features
b) Other order
I gave the more detailed description below if it helps. 

Best,
Furkan

 ---

**DETAILS**

Just FYI, I keep the list of feature names in `list_of_features` .

There are several ways to assign those feature importance scores to the corresponding features:

- Way 1: Direct matching

In this way, we can assume that feature importance are in the same order with features given to the model so that we can use the following for matching them:
`feature_importances = { k: v for k, v in zip(list_of_features, clf.feature_importances_) }`

- Way 2: Using np.argsort

In this way (where the several Kaggle kernels also use: [example 1](https://www.kaggle.com/optimo/tabnet-with-loop-feature-engineering-explained#Basic-Features-importance), [example 2](https://www.kaggle.com/carlmcbrideellis/tabnet-and-interpretability-jane-street-example)), the indices of the features (either in ascending or descending order) can be used to match to the corresponding feature name:

```
feat_attributes = clf.feature_importances_
indices = np.argsort(feat_attributes)
feat_names = [list_of_features[idx] for idx in indices]
feature_importances = { k: v for k, v in zip(feat_names, feat_attributes) }
```

As mentioned above, `indices` could be also `np.argsort(feat_attributes)[::-1]`.

**Expected behavior**
I would expect that the order of `model.feature_importances_` is documented to be sure that mapping those feature values into the feature names is true.

So, what way should we map the feature importance scores?

**Comment by Optimox** [comment]
Hello @furkanmtorun,

If you think about what the model sees and how much information it has there is no ambiguity about feature importances.

You give your input features to the model using a numpy array. The order of your columns in your numpy array dictates the order of your features from the `model.feature_importances_`. I don't see another way of ordering the feature_importances than the order of the features themselves.

You never need to give the model the features names, so it can't check for a 'correct' matching.

It seems to me the two ways you are referring to are correct and based on the same paradigm I explained above, it' just a matter of ordering for plotting.

I'm not sure to understand what you are asking for? A clearer explanation in the README?

**Comment by furkanmtorun** [comment]
Hey @Optimox ,

Thank you very much for your prompt response!
So, now, I directly map the features to their scores as is expected.
