### ISSUE TITLE
Character level encoding?

### ISSUE THREAD

**Issue by zippeurfou** [dreamquark-ai/tabnet#326]
## Feature request

I would like to be able to apply a "character level" type of categorical data.

**What is motivation or use case for adding/changing the behavior?**

I think to understand the implementation, understanding the problem would help as this could be implemented in a more general way. 
Imagine you have a dataset of users email, first name, last name, a few more categorical and numerical data and a target variable which is is_real_user.
The goal is to distinguish between fake and real users. 
One observation you do is that there is a certain pattern in the first/last name and email for fake users.
Ie. Real first name could be Francis but fake one would be zz123.
You also have less than 10k entries so you will most likely have no duplicate on first and last name.
Therefore doing an embedding on the first / last name and email address are not going to help.
One way you could solve it is to extract n grams and other features from the textual features (is. Has number, has capital letter..) anything that can help the model basically understand it and just send theses input.
However, another way which could also be successful is to have a character level RNN on the first name, last name, email address that would basically learn what a legit first name, last name and email looks like. Then you could combine them together by for example treating the encoding as numerical features in tabnet.

Additionally, this could also be applied for others use cases. Ie. You have a picture as one of the features and want to apply a network to encode the picture but would like the model to train on some of the last layers (freeze a bunch of layer and have a few not frozen) as it is also training on other features. 

One potential solution is to allow for the numerical features to be from a network that can be trained as part of the general training of tabnet. 

**Are you willing to work on this yourself?**

I am happy to look into it.

**Comment by Optimox** [comment]
I think this could be feasible but some difficulties will arise.

Your first model would need to give some information to the model class like what is the output size of the model to be used as input size for Tabnet, you will also need to specify where are the categorical columns of your model. You'll lose the explanability of TabNet as well. You'll need to change all this without breaking the current behavior...

If you want to try and open a PR please feel free to do so, I'll try to help.

**Comment by zippeurfou** [comment]
Thanks @Optimox, I am not sure how much I will be able to work on this but I appreciate it.

**Comment by zippeurfou** [comment]
Another way this could be handled is with a new "text" type of input (so categorical, numerical and text).
Text columns are separated by a token ie. `[SEP]` and then you take the `[CLF]` output of the network.
Combining could be done as a numerical feature in the current model.

**Comment by Optimox** [comment]
I'm closing this, feel free to reopen if you decide to work on this or have more information to share.
