### ISSUE TITLE
docker: Error response from daemon: Unknown runtime specified nvidia.

### ISSUE THREAD

**Issue by novinsh** [dreamquark-ai/tabnet#333]
**Describe the bug**

Docker does not run with the runtime parameter `nvidia` from the command: `make start-gpu`

**What is the current behavior?**
Using the make start-gpu I get the following error:
```
docker: Error response from daemon: Unknown runtime specified nvidia.
See 'docker run --help'.
make: *** [Makefile:50: start-gpu] Error 125
```
The whole dump of the error message is available from [here](https://paste.ubuntu.com/p/hBcfpDHZ4G/).

**If the current behavior is a bug, please provide the steps to reproduce.**

I am not 100% sure how it could be reproduced but this [thread](https://github.com/NVIDIA/nvidia-docker/issues/838) might provide some insights.

**Expected behavior**

The docker must be run and all requirements must be installed without a problem via the installation/build script prior to [line 50 in the Makefile](https://github.com/dreamquark-ai/tabnet/blob/b6e1ebaf694f37ad40a6ba525aa016fd3cec15da/Makefile#L50). It appears that installing `nvidia-docker2` is what is required as mentioned [here](https://github.com/NVIDIA/nvidia-docker/issues/838#issuecomment-636655245). And the installation could be followed from [here](https://cnvrg.io/how-to-setup-docker-and-nvidia-docker-2-0-on-ubuntu-18-04/).

**Screenshots**

NA

**Other relevant information:**
poetry version:  1.1.11
python version: 3.8.5
Operating System: 5.8.0-38-generic #43~20.04.1-Ubuntu
Additional tools: NA

**Additional context**

NA

**Comment by Optimox** [comment]
I guess we now that the library is available using pypi there is no real need for a special docker environment, you could start from any docker container and simply pip install tabnet inside the container.

We can't really provide help on how to install docker containers with nvidia-docker.

**Comment by novinsh** [comment]
The `make start-gpu` must be run without any error for the end-user.  I reckon as other requites are installed from `Dockerfile_gpu`  `nvidia-docker2` could also be one.

Also, installing tabnet via `pip` I don't get the latest version so that is why I wanted to run with docker directly form the repo.
