### ISSUE TITLE
TabNet on Reinforcement Learning

### ISSUE THREAD

**Issue by muztaba40** [dreamquark-ai/tabnet#343]
## Feature request
As TabNet works for Supervise and unsupervised learning (accoding to journal). But how it is behaved in Reinforcement Learning (RL)? For instance offline RL.

**What is the expected behavior?**
Better rewards in future against classical algorithms. 

**What is motivation or use case for adding/changing the behavior?**
As data from sensors come as in tabular format it could be better to use TabNet

**How should this be implemented in your opinion?**
Feed features (velocity, position of nearby vehicles, padestrain) as BN in TabNet architecture and try to out better movement.

**Are you willing to work on this yourself?**
yes

**Comment by Optimox** [comment]
Tabnet is just a specific architecture, it’s not related to a reinforcement learning paradigm.

However, you can for sure use tabnet as a predictor inside a reinforcement learning algorithm.

But this is out of scope of the library and tabnet will only be a tiny piece of a larger project.

I can’t really help you with that, only thing I can say is that tabnet is not the go to algorithm if you are willing to start doing reinforcement learning.

Please share with us your results when you get some! 

Best
