### ISSUE TITLE
The Agg. code

### ISSUE THREAD

**Issue by 7568** [dreamquark-ai/tabnet#344]
## Feature request

please help me, I can't find the code about Agg. Or the Agg. is the abbreviation of some words? Please help me, thanks!

![image](https://user-images.githubusercontent.com/4082491/144603055-9b24d59a-bd90-4350-9b44-3a23ec54f7fb.png)

**What is the expected behavior?**

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by Optimox** [comment]
The aggregation here is the sum of the ReLU activation for each step (considered as the importance of this step in the final prediction).

The line of code that does that is here : https://github.com/dreamquark-ai/tabnet/blob/5ac55834b32693abc4b22028a74475ee0440c2a5/pytorch_tabnet/tab_network.py#L195

**Comment by 7568** [comment]
thank you very much.
