### ISSUE TITLE
Add a `conda` install option for `pytorch-tabnet`

### ISSUE THREAD

**Issue by sugatoray** [dreamquark-ai/tabnet#346]
## Feature request

A `conda` installation option could be quite helpful as an alternative alongside the ability to install `pytorch-tabnet` with `pip`. I have already done the work necessary to make `pytorch-tabnet` available on `conda-forge`. (PR: https://github.com/conda-forge/staged-recipes/pull/17292)

Now you can install `pytorch-tabnet` as:

```sh
conda install -c conda-forge pytorch-tabnet
```

> Note: the PR was just merged. Give it some 2-3 hours and it will be ready for use.

:bulb: **I will send a PR to update the docs/readme.**

**Comment by sugatoray** [comment]
cc: @Optimox @Hartorn 

A screenshot says it all! :fireworks: 

![image](https://user-images.githubusercontent.com/10201242/146641038-75692baa-7dfa-4146-908d-ed4870f1ba70.png)

**Comment by sugatoray** [comment]
> Note: the PR was just merged. Give it some 2-3 hours and it will be ready for use.

**Comment by Hartorn** [comment]
Nice work :)

**Comment by Hartorn** [comment]
Is there anything for us to do, to maintain this ?

**Comment by sugatoray** [comment]
@Hartorn It will be nice if you could nominate someone (you or someone of your choice who could be a comaintainer with me of the conda-forge feedstock that maintains the package on conda-forge channel. So, who do you propose?

**Comment by Hartorn** [comment]
@sugatoray You can add @Optimox @Hartorn @eduardocarvp also, but, not sure I will have time to do this honestly

I guess @Optimox is the more active here.

**Comment by sugatoray** [comment]
> Is there anything for us to do, to maintain this ?

@Hartorn Yes, there is a PR (#347) that I raised. If you could take a look at it and merge it, that will be great.

For long term maintainability, I will add @Optimox @Hartorn @eduardocarvp to the feedstock and walk you through the easy simple steps you need to do after each PyPI release you make. This will enable you to keep both PyPI and conda-forge versions in sync. As a co-maintainer, obviously, if you have questions, I will be there. Sounds good?

**Comment by sugatoray** [comment]
Any idea, when your next release could be scheduled?

**Comment by Hartorn** [comment]
> For long term maintainability, I will add @Optimox @Hartorn @eduardocarvp to the feedstock and walk you through the easy simple steps you need to do after each PyPI release you make. This will enable you to keep both PyPI and conda-forge versions in sync. As a co-maintainer, obviously, if you have questions, I will be there. Sounds good?

I think we need to update the release script then, to include those steps in it

> Any idea, when your next release could be scheduled?

@Optimox Any idea ?

**Comment by sugatoray** [comment]
@Hartorn Here is the :star:[LinkedIn share](https://www.linkedin.com/posts/sugatoray_tabnet-pytorch-tabnet-activity-6877998887932633088-SELH) on making `pytorch-tabnet` available on conda-forge.

![image](https://user-images.githubusercontent.com/10201242/146647349-32307682-7f6b-4ce9-aa69-6c61e0e27912.png)

**Comment by eduardocarvp** [comment]
Nice work :)

#347 looks good to me as well, just got to reword your commit in order to comply to conventional commits.

We just have to merge #348 and then we will probably make a release as soon as it's done. I see no problem on merging #347 as well before the next release. So to give a proper answer, probably next week for the next release.

I would be super down to look into the steps after the PyPI release to keep both projects in sync, do you have access to the project Slack, @sugatoray ? We can talk over there and would be great if we could include all we need on our release scripts.

**Comment by sugatoray** [comment]
> do you have access to the project Slack?

Yes. Just joined.

**Comment by Optimox** [comment]
Thanks @sugatoray,

Very nice contribution as a lot of people use conda!

As @Hartorn suggested, I think we should somehow automate the push to conda so that we do not have to think twice when making a new release.

About the date of the next release, it should be fairly soon, we could aim to release before the end of the year.

**Comment by sugatoray** [comment]
> Thanks @sugatoray,
> 
> 
> 
> Very nice contribution as a lot of people use conda!
> 
> 
> 
> As @Hartorn suggested, I think we should somehow automate the push to conda so that we do not have to think twice when making a new release.
> 
> 
> 
> About the date of the next release, it should be fairly soon, we could aim to release before the end of the year.

Well, conda-forge already has some automation in place.

It's not a best practice in conda-forge to *completely* automate this. It's in fact, much simpler a step, and should be thoroughly checked before pushing to conda-forge. You don't automatically merge without reviewing here, right?

What I would suggest you is to send a PR to `conda-forge/pytorch-tabnet-feedstock` with an updated recipe the next time you have a PyPI release and then let me review it as the maintainer before I merge it. Initially, let's do this a few times, so you could get comfortable with the process. 

If you must automate, you can automate on your end here. But the PR review at conda-forge must remain a manual step.

All you have to do is update the file: `recipe/meta.yaml`

Change:

- `version` (same as PyPI release)
- `sha256` (same as PyPI release)
- update dependencies version-specifications (same as PyPI release), if necessary. 

So, if you would like to write a script that would create the `meta.yaml` file, that's fine. But that should remain here in this repository, to help you raise a PR to the feedstock repo. 

A few key things to remember, if you want some automation on your end (in this repo):

- the conda-forge packages may not always have the same names as their PyPI counterparts. So, need to maintain a mapping here to automate. 

- the automation should use the current recipe as the base template.

- you can use a simple jinja2 based automation on your end to push to the feedstock as a PR. 

> *However, I would suggest you to update manually, as the work involved is really simple and quick*.

**Comment by Optimox** [comment]
@sugatoray yes I guess we would like to automate as much as possible.

With poetry we are actually just automatically pushing the changes to pypi when we make a release, which is much simpler. But I guess it should not be a problem to remember to push on conda as long as it's not too difficult.

**Comment by sugatoray** [comment]
@Optimox I understand the reason behind why you want to automate as much as possible: _reduce technical debt_. I am personally a heavy supporter of automation. Let me know if you need any help with that.
