### ISSUE TITLE
How to use TabNet for unsupervised task ( clustering )?

### ISSUE THREAD

**Issue by monk1337** [dreamquark-ai/tabnet#355]
Hello TabNet Developers, I am dealing with a dataset that contains both continuous and categorical data points, There are no labels in the dataset and the task is to cluster the data points.

I was wondering is it possible to use the tablet for clustering?

**Comment by Optimox** [comment]
Hello @monk1337,

Similar questions have been asked here #303 and here #149.

So my answer is similar:
- I don't think TabNet is the go to solution for such a problem
- however you can use TabNetPretrainer to learn something from your unlabelled data, then retrieve the prediction before the final mapping (this is not directly available but can be accessed as explained in #149). Once you have extracted your rows' representations you can use any unsupervised clustering model (KMeans etc...).
