### ISSUE TITLE
IndexError: index out of range in self

### ISSUE THREAD

**Issue by Sayantad** [dreamquark-ai/tabnet#357]
**Describe the bug**
I have trained tabnet on tabular data

These are configuration
# TabNetPretrainer
unsupervised_model = TabNetPretrainer(
    n_d=32, n_a=32, n_steps=5,
    cat_idxs=cat_idxs,
    cat_dims=cat_dims,
    cat_emb_dim=4,
    optimizer_fn=torch.optim.Adam,
    optimizer_params=dict(lr=2e-2),
    mask_type='entmax', # "sparsemax",
    n_shared=2, # nb shared glu for decoding
    n_independent=2, # nb independent glu for decoding
)

unsupervised_model.fit(
    X_train=X_train,
    eval_set=[X_valid],
    max_epochs=max_epochs , patience=10,
    batch_size=8, virtual_batch_size=128,
    num_workers=0,
    drop_last=False,
    pretraining_ratio=0.8,
) 

clf = TabNetClassifier(optimizer_fn=torch.optim.Adam,
                       optimizer_params=dict(lr=2e-2),
                       scheduler_params={"step_size":10, # how to use learning rate scheduler
                                         "gamma":0.9},
                       scheduler_fn=torch.optim.lr_scheduler.StepLR,
                       mask_type='sparsemax' # This will be overwritten if using pretrain model
                      )
clf.fit(
    X_train=X_train, y_train=y_train,
    eval_set=[(X_train, y_train), (X_valid, y_valid)],
    eval_name=['train', 'valid'],
    eval_metric=['accuracy'],
    max_epochs=max_epochs , patience=20,
    batch_size=8, virtual_batch_size=128,
    num_workers=0,
    weights=1,
    drop_last=False,
    from_unsupervised=loaded_pretrain
    
) 
saved_filepath = clf.save_model(saving_path_name)
loaded_clf = TabNetClassifier()
loaded_clf.load_model(saved_filename)

Every thing is working fine on my split train./valid/test data. but  when I am doing inference pn inference data and get the index out of range in self 

IndexError                                Traceback (most recent call last)
Input In [96], in <module>
----> 1 preds = loaded_clf.predict_proba(data)

File ~/anaconda3/envs/geopy39/lib/python3.9/site-packages/pytorch_tabnet/tab_model.py:102, in TabNetClassifier.predict_proba(self, X)
     99 for batch_nb, data in enumerate(dataloader):
    100     data = data.to(self.device).float()
--> 102     output, M_loss = self.network(data)
    103     predictions = torch.nn.Softmax(dim=1)(output).cpu().detach().numpy()
    104     results.append(predictions)

File ~/anaconda3/envs/geopy39/lib/python3.9/site-packages/torch/nn/modules/module.py:1102, in Module._call_impl(self, *input, **kwargs)
   1098 # If we don't have any hooks, we want to skip the rest of the logic in
   1099 # this function, and just call forward.
   1100 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102     return forward_call(*input, **kwargs)
   1103 # Do not call functions when jit is used
   1104 full_backward_hooks, non_full_backward_hooks = [], []

File ~/anaconda3/envs/geopy39/lib/python3.9/site-packages/pytorch_tabnet/tab_network.py:582, in TabNet.forward(self, x)
    581 def forward(self, x):
--> 582     x = self.embedder(x)
    583     return self.tabnet(x)

File ~/anaconda3/envs/geopy39/lib/python3.9/site-packages/torch/nn/modules/module.py:1102, in Module._call_impl(self, *input, **kwargs)
   1098 # If we don't have any hooks, we want to skip the rest of the logic in
   1099 # this function, and just call forward.
   1100 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102     return forward_call(*input, **kwargs)
   1103 # Do not call functions when jit is used
   1104 full_backward_hooks, non_full_backward_hooks = [], []

File ~/anaconda3/envs/geopy39/lib/python3.9/site-packages/pytorch_tabnet/tab_network.py:849, in EmbeddingGenerator.forward(self, x)
    846         cols.append(x[:, feat_init_idx].float().view(-1, 1))
    847     else:
    848         cols.append(
--> 849             self.embeddings[cat_feat_counter](x[:, feat_init_idx].long())
    850         )
    851         cat_feat_counter += 1
    852 # concat

File ~/anaconda3/envs/geopy39/lib/python3.9/site-packages/torch/nn/modules/module.py:1102, in Module._call_impl(self, *input, **kwargs)
   1098 # If we don't have any hooks, we want to skip the rest of the logic in
   1099 # this function, and just call forward.
   1100 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102     return forward_call(*input, **kwargs)
   1103 # Do not call functions when jit is used
   1104 full_backward_hooks, non_full_backward_hooks = [], []

File ~/anaconda3/envs/geopy39/lib/python3.9/site-packages/torch/nn/modules/sparse.py:158, in Embedding.forward(self, input)
    157 def forward(self, input: Tensor) -> Tensor:
--> 158     return F.embedding(
    159         input, self.weight, self.padding_idx, self.max_norm,
    160         self.norm_type, self.scale_grad_by_freq, self.sparse)

File ~/anaconda3/envs/geopy39/lib/python3.9/site-packages/torch/nn/functional.py:2044, in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   2038     # Note [embedding_renorm set_grad_enabled]
   2039     # XXX: equivalent to
   2040     # with torch.no_grad():
   2041     #   torch.embedding_renorm_
   2042     # remove once script supports set_grad_enabled
   2043     _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 2044 return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)

IndexError: index out of range in self

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**

It should work when I load model and data at the time of inferance

**Screenshots**

**Other relevant information:**
poetry version:  
python version: 
Operating System: 
Additional tools:

**Additional context**

**Comment by eduardocarvp** [comment]
Hello @Sayantad ,

It seems at first glance that your test set has one more classes on some embedded feature compared to the training set. Could you check that the values on the test set of all the categorical features that go through embedding are a subset of the values found in the training set?

**Comment by Optimox** [comment]
I think @eduardocarvp is right, but the error message could be clearer indeed...

**Comment by Optimox** [comment]
@Sayantad have you found the error?

**Comment by ooghry** [comment]
I had the same problem and in my opinion, it would be nice to show a better message.
Actually, I split train and test and validate data, then looped over training data for categorical_dims.

**Comment by Sayantad** [comment]
> Hello @Sayantad ,
> 
> It seems at first glance that your test set has one or more classes on some embedded feature compared to the training set. Could you check that the values on the test set of all the categorical features that go through embedding are a subset of the values found in the training set?

Yes, you are correct. I handle this issue in my inference script and it work fine. Thanks
