### ISSUE TITLE
Unseen categorical data

### ISSUE THREAD

**Issue by wilmerhenao** [dreamquark-ai/tabnet#359]
Hi. What happens when I train a model and it turns out that the test set contains some unseen categorical observation. Do I have to retrain the whole model with extra "unknown" observations or is this handled internally?

Thanks!

**Comment by Optimox** [comment]
Hello @wilmerhenao,

You'll get an error since the embedding index will be out of range.
You can decide to deal with this issue during label encoding of your test set (no need to retrain) or create a specific unknown categorie during training and use it during test.
