### ISSUE TITLE
ValueError: multi_class must be in ('ovo', 'ovr')

### ISSUE THREAD

**Issue by adupatil** [dreamquark-ai/tabnet#360]
**Describe the bug**
I'm trying to use TabnetClassifier for multiclass classification with 758 features and 5 classes but on running it gives me ValueError

X = 758 features
y = Labelencoded classes (0-4)
**What is the current behavior?**

Traceback (most recent call last):
  File "tabnet_.py", line 53, in <module>
    model(pd.read_csv("./cat3_clust.csv",dtype={'id':'str'}))
  File "tabnet_.py", line 45, in model
    weights=1,
  File "/home/adwait/miniconda3/envs/r_env/lib/python3.7/site-packages/pytorch_tabnet/abstract_model.py", line 227, in fit
    self._predict_epoch(eval_name, valid_dataloader)
  File "/home/adwait/miniconda3/envs/r_env/lib/python3.7/site-packages/pytorch_tabnet/abstract_model.py", line 510, in _predict_epoch
    metrics_logs = self._metric_container_dict[name](y_true, scores)
  File "/home/adwait/miniconda3/envs/r_env/lib/python3.7/site-packages/pytorch_tabnet/metrics.py", line 142, in __call__
    res = metric(y_true, y_pred)
  File "/home/adwait/miniconda3/envs/r_env/lib/python3.7/site-packages/pytorch_tabnet/metrics.py", line 206, in __call__
    return roc_auc_score(y_true, y_score[:, 1])
  File "/home/adwait/miniconda3/envs/r_env/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 560, in roc_auc_score
    raise ValueError("multi_class must be in ('ovo', 'ovr')")
ValueError: multi_class must be in ('ovo', 'ovr')

**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**

It should fit the model on multiple classes and then predict but the model gives error while fitting
**Screenshots**

**Other relevant information:**
poetry version:  
python version: 3.7.6
Operating System: Linux
Additional tools: 

**Additional context**

from pytorch_tabnet.tab_model import TabNetClassifier
import torch
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
np.random.seed(0)
from pathlib import Path
import sys

def model(data):
    x1_index = list(data.columns).index('x1')
    if 'r' in data.columns:
        y = data['r']
    else:
        y = data['Class']
    D = {'R0':0,'R1':1,'R2':2,'R3':3,'R4':4}
    y = y.map(D)
    X = data.drop(list(data.columns)[:x1_index],axis=1)
    X = pd.DataFrame(X.values,columns=np.arange(0,X.shape[1]))
    print(X.head(10))
    print(y.head(10))
    # sys.exit()
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=42)

    tabnet_params = {"optimizer_fn":torch.optim.Adam,
                 "optimizer_params":dict(lr=2e-2),
                 "scheduler_params":{"step_size":50, # how to use learning rate scheduler
                                 "gamma":0.9},
                 "scheduler_fn":torch.optim.lr_scheduler.StepLR,
                 "mask_type":'entmax' # "sparsemax"
                }

    clf = TabNetClassifier(**tabnet_params)
    print(y_train.shape)
    clf.fit(
        X_train=X_train.values, y_train=y_train.values,
        eval_set=[(X_train.values, y_train.values), (X_test.values, y_test.values)],
        eval_name=['train', 'valid'],
        eval_metric=['auc'],
        max_epochs=40 , patience=5,
        batch_size=1024, virtual_batch_size=128,
        num_workers=0,
        weights=1,
    )

    pred = clf.predict(X_test.values)

    print(classification_report(y_test,pred))

if __name__ == "__main__":
    model(pd.read_csv("./cat3_clust.csv",dtype={'id':'str'}))

**Comment by adupatil** [comment]
I used the wrong eval metrics

**Comment by Optimox** [comment]
@adupatil yes AUC can't be computed for multi-class classification setting.
