### ISSUE TITLE
Device is not actually using gpu

### ISSUE THREAD

**Issue by dzheng-pitt** [dreamquark-ai/tabnet#361]
**Describe the bug**

I train the model with device_name == 'cuda' or left as default to use the gpu but trains on cpu instead.
**What is the current behavior?**
I train the model with device_name == 'cuda' or left as default to use the gpu but trains on cpu instead. It finds Device used : cuda but doesn't seem to use the gpu

**If the current behavior is a bug, please provide the steps to reproduce.**

```
from pytorch_tabnet.multitask import TabNetMultiTaskClassifier
import optuna
import pandas as pd
import numpy as np

import utils

utils.get_latest_round_data(tournament_only=False)

train_data = utils.load_data('training')
valid_data = utils.load_data('validation')

train_data = train_data.dropna()
valid_data = valid_data.dropna()

targets, features = utils.get_targets_features(train_data)

X_train = train_data[features].values
Y_train = (train_data[targets].values*12).astype('int')

X_valid = valid_data[features].values
Y_valid = (valid_data[targets].values*12).astype('int')

clf = TabNetMultiTaskClassifier(device_name = 'cuda') 
clf.fit(X_train, Y_train,
        eval_set=[(X_train, Y_train), (X_valid, Y_valid)])
```

**Expected behavior**

It should train on gpu
**Screenshots**

![image](https://user-images.githubusercontent.com/98243903/154788309-d3863e05-8bc7-4bc9-b1fa-76853b06de70.png)

**Other relevant information:**

**Additional context**

**Comment by Optimox** [comment]
Pytorch-tabnet is using pytorch, you need a working installation compatible with your gpu to make it work: `torch.cuda.is_available` must return `True`.

This is related to how torch is installed, please refer to pytorch installation documentation.

**Comment by dzheng-pitt** [comment]
Hey, thanks for the reply, I can take a look at the GPU load with varying batch sizes. 

During training before (the picture), the CPU load is sometimes over 50%, it just happened to be 10% at that point in the screen shot, but I am pretty sure it is using the CPU to do something which I assumed was training because the GPU % was always 0 here during the first epoch and there are something like 2.5M observations in the training dataset. 

I also almost exclusively use gpu training in pytorch with other things and usually my GPU load is 20% so this was peculiar for me to see.

**Comment by dzheng-pitt** [comment]
I did find using a batch size of 4000k, the GPU load was about 1% and the CPU load was 40%. This is expected? I don't feel I usually see this when using pytorch, but I am also using doing something with NLP or CV.

![image](https://user-images.githubusercontent.com/98243903/154828382-b9dc6d26-d921-49a8-a15e-a67d2c5046bb.png)

**Comment by Optimox** [comment]
Tabular data are much smaller than images:
- single RGB image 512*512*3>780K floating points, you can probably go with a batch size of 16-32 with a 12Go GPU and resnet18
- basic tabular data will contains 100 features in a float format so you would need  a batch size ~ 7800 time bigger to fill your gpu the same way, which would be a batch size around 250K-500K

The original TabNet paper mentions that you can take a batch size around ~10% of the total data to train the algorithm. I would not recommend to use a batch size of 250K but you can definitely try 2**10 to 2**14.

Anyway, I think you should simply check that things are going way faster when using your GPU than your CPU. Then don't worry too much about where the computation is done. (The reason why your CPU is being used is that not everything happens on the GPU - dataloading is done on cpu, metrics computation too...)

**Comment by Optimox** [comment]
@dzheng-pitt did you manage to solve your problem ?

**Comment by dzheng-pitt** [comment]
Yes! It was all good now. Thank you!

**Comment by Optimox** [comment]
So just to understand, you just increased the batch size to see that the GPU was used ? What happened ?

**Comment by dzheng-pitt** [comment]
Yes, like you said it was a bit faster, and I saw the GPU utilization increase to a couple percent.

**Comment by tanweer-mahdi** [comment]
Don't we need to transfer the torch tensors before training the TabNet? Like the following

`import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

## Let's say X_train is a pandas dataframe

# moving to tensor
X_train = torch.from_numpy(X_train).to(device)
`
Is the above step redundant?

**Comment by Optimox** [comment]
@tanweer-mahdi there is no need to do that, things are handled internally and everything is working fine if you GPU is recognized by pytorch.
