### ISSUE TITLE
Is it possible to use numeric vector as a feature?  

### ISSUE THREAD

**Issue by puzzlecollector** [dreamquark-ai/tabnet#362]
I am wondering if it is possible for me to use a numeric vector as one of the input features for TabNet. 

To be specific, I am planning to encode some text data using BERT, and I am planning to the use 768 dimension vector output (CLS token representation) from BERT. So I will end up with features of type 

1. Categorical 
2. Categorical
3. Categorical
4. Numeric
5. Numeric
6. Numeric
7. Numeric
....
n-1. Numeric 
n. 768-d numeric vector 

something like this.

**Comment by Optimox** [comment]
Hello @puzzlecollector,

I'm sorry I don't understand your question. Could you try to elaborate ?

**Comment by puzzlecollector** [comment]
@Optimox can tabnet take in vector input features? So instead of a feature being some number of a categorical variable, can it be a vector?

**Comment by Optimox** [comment]
@puzzlecollector,

If all the input features are vectors of same length then you should probably use convolutions.

**Nevertheless:**
If the vectors don't have the same length the best approach is probably to flatten and concatenate all of them. Then you can use TabNet with flattened array. I think it's ok to do so, and you can see it as a preprocessing step : either give all the vector features to the model, or you could compute statistics and only give statistics to the model to lower the number of features.

Hope this helps

**Comment by Optimox** [comment]
Closing this issue, feel free to reopen for further discussion.
