### ISSUE TITLE
y_train should be of shape (n_examples, n_tasks)but got (1837,)

### ISSUE THREAD

**Issue by SamiurRahman1** [dreamquark-ai/tabnet#365]
Hi, my tabular dataset has 81 features and it is a multi-class classification problem. When i run:
`tabnet = TabNetMultiTaskClassifier();
tabnet.fit(X_train, y_train);
tabnet_preds = tabnet.predict(X_test)`
i get the following error:
`y_train should be of shape (n_examples, n_tasks)but got (1837,)`. My y_train is a numpy array and i have made sure that X_train and y_train has the same length. Could you please help with this problem?

**Comment by Optimox** [comment]
You should use TabNetClassifier instead of multi task classifier since you are on a classification setting.

**Comment by SamiurRahman1** [comment]
thanks for your reply. So, i misunderstood? i am classifying 5 classes here. i thought `TabNetMultiTaskClassifier()` is for multiclass classification
