### ISSUE TITLE
How to get the prediction of a single instance?

### ISSUE THREAD

**Issue by SamiurRahman1** [dreamquark-ai/tabnet#366]
Hi! I am trying to get the prediction of a single instance with the `predict` function. I can get the prediction of a batch with:
`tabnet.predict(X_test.values)`, but when i do
 `instanceVal = portmap_data.iloc[instance_num] ,
prediction_value = tabnet.predict(instanceVal.values)`, i get an error. Any help would be appreciated. :)

**Comment by Optimox** [comment]
What is your error?

**Comment by SamiurRahman1** [comment]
when i run 
`instanceVal = portmap_data.iloc[instance_num]`
`prediction_value = tabnet.predict(instanceVal.values)`
i get: `[ValueError: expected 2D or 3D input (got 1D input)]()`

**Comment by SamiurRahman1** [comment]
the same error occurs when i run  `prediction_value = tabnet.predict(portmap_data.values[instance_num])`.
p.s.  `portmap_data` is a pandas dataframe.

**Comment by Optimox** [comment]
you probably need a matrix as input. Can you try `instanceVal = portmap_data.iloc[instance_num].values.resape(1, -1)` and let me know if this works ?

**Comment by SamiurRahman1** [comment]
The solution worked! thanks a lot!
