### ISSUE TITLE
categorical variables in input

### ISSUE THREAD

**Issue by puzzlecollector** [dreamquark-ai/tabnet#369]
When passing inputs into TabNet, do I have to specify which features are categorical? or does TabNet automatically detect categorical features? I have a round 900 input features and out of them around 70 are categorical features, and I have passed all these features in without specifying which features are categorical, but I still seem to get pretty good accuracy results.  However, looking at the readme file, it seems like I need to specify the categorical indices. 

<img width="773" alt="Screen Shot 2022-03-16 at 5 23 54 PM" src="https://user-images.githubusercontent.com/15623464/158547413-50372cd6-5cf1-4272-8575-327a4f07f13b.png">

**Comment by Optimox** [comment]
Hello @puzzlecollector,

Your code is working without specifying anything because your categorical features are in ordinal format (integers), it would break otherwise.
The model can be trained with ordinal categories without specifying anything, however if you do so, the model will consider them as numerical features, and the order of your categories will matter quite a lot.

If you specify `cat_idxs, cat_dims and cat_emb_dim` then the model will first embed every categorical feature before going into the tabnet architecture. This should potentially improve your score.

You can have a look at this example as a starter point: https://github.com/dreamquark-ai/tabnet/blob/develop/census_example.ipynb

Let us if your score improves when using embeddings!

**Comment by puzzlecollector** [comment]
@Optimox 

I see I'll try with specifying cat_idxs, cat_dims and cat_emb_dim. I have a feeling that it should improve the score too :) 

Another question is I've been using ```TabNetMultiTaskClassifier``` although I am trying to do binary classification. Would using ```TabNetMultiTaskClassifier``` on a binary classification task instead of ```TabNetClassifier ``` affect performance? (I am thinking that it probably won't but I just want to make sure).

**Comment by puzzlecollector** [comment]
@Optimox 
If I reshape my target variable shape to (batch_size, 1), then it seems that it can also do binary classification. 

```
input_features = []
for col in train_df.columns:
    if col != 'target' and col != 'Years':
        input_features.append(col) 
        
X_train = train_df[input_features].values
Y_train = train_df['target'].values 
Y_train = Y_train.reshape((-1,1))

X_val = val_df[input_features].values
Y_val = val_df['target'].values 
Y_val = Y_val.reshape((-1,1))

X_test = test_df[input_features].values
Y_test = test_df['target'].values 
Y_test = Y_test.reshape((-1,1)) 

from pytorch_tabnet.multitask import TabNetMultiTaskClassifier 

clf = TabNetMultiTaskClassifier() 

clf.fit(
    X_train, Y_train, 
    eval_set=[(X_val, Y_val)], 
    eval_metric = ['accuracy', 'balanced_accuracy'],
    max_epochs = 500, 
    patience = 500
)
```

If I execute this code everything seems to run fine. I have tried changing TabNetMultiTaskClassifier to TabNetClassifier, and they seem to have pretty much the same performance.

**Comment by puzzlecollector** [comment]
@Optimox 
Also I have looked at the code you provided (https://github.com/dreamquark-ai/tabnet/blob/develop/census_example.ipynb) 
and it seems like cat_emb_dim is set to 1. Is it usually normal to set the embedding dimension to 1? All the categorical features have unique values less than 7 (most categorical variables have 2 values, and the day of the week categorical variable has 7 values)

**Comment by puzzlecollector** [comment]
@Optimox Also I saw a 3% increase in accuracy (with out of sample data) when I used embeddings for categorical embeddings! so it does make a difference :)

**Comment by Optimox** [comment]
Good to hear!
