### ISSUE TITLE
F-score metrics

### ISSUE THREAD

**Issue by balazsgonczy** [dreamquark-ai/tabnet#375]
Hi,

Is it possible to extract not just the accuracy but the final f-score metrics of the model as well?

Best,

balazs

**Comment by Optimox** [comment]
Yes you can customize both the loss function and the evaluation metrics, there is a custom example notebook in the repo that shows how to do it.

Don’t hesitate to ask for help if needed.

**Comment by Optimox** [comment]
@balazsgonczy did you find what you were looking for?

**Comment by Optimox** [comment]
Feel free to reopen if needed.
