### ISSUE TITLE
F-score implementation issues

### ISSUE THREAD

**Issue by balazsgonczy** [dreamquark-ai/tabnet#380]
Dear Optimox,

I am struggling with the custom F-score implementation. It should be working, because the logic I am implementing is following your GINI examples workflow.

I am using the following code:

"

from pytorch_tabnet.metrics import Metric

class F1_score(Metric):
    def __init__(self):
        self._name = "f1_score"
        self._maximize = True

    def __call__(self, y_true, y_pred):
        return f1_score(y_true, y_pred[:, 1], average='weighted')
"

Error message:
"
TypeError: init() missing 2 required positional arguments: 'y_true' and 'y_pred'
"

Can you give me suggestion what am I doing wrong?

Thx,

Balázs

**Comment by balazsgonczy** [comment]
I restarted it from scratch and now I'm getting this message: "ValueError: Classification metrics can't handle a mix of binary and continuous targets"

**Comment by eduardocarvp** [comment]
Hi @balazsgonczy,

It looks more like a problem when calling sklearn's f1_score than with your own function.
The thing is that the F1 score is computed at fixed threshold, so you cannot use the raw y_score when computing the metric, but the actual prediction (0 or 1) for a given threshold.

For example:

- `f1_score([0.1, 0.2, 0.3, 0.4], [0, 1, 0, 1])` fails with `ValueError: Classification metrics can't handle a mix of continuous and binary targets`
- `f1_score([0, 1, 0, 0], [0, 1, 0, 1])` returns 0.6666666666666666

**Comment by balazsgonczy** [comment]
Hi @eduardocarvp,

This is exactly what I suspected, but I think the issue is a little bit more serious. I have tried to contact my friend who is a CS student as well and a professional in python. We tried this approach but we got 2 bugs that we have never seen before. I run the code in Google Colab and VScode as well. We got 2 bugs:

1. Changing errors with f1_score metric from sklearn. -> The issue is something like what you have suggested.
2. I think there is a hidden bug in the workflow which reckts Google Colab and VScode if this error happens. I have to totally restart the kernel in order to run any further code from that point when I encountered error 1. It looks like its rerunning if I modify parts of the code in the metrics class but no it is just returning the same error message in spite of making dramatic changes like printing out parameters or shape of it (but it won't return anything).

Could you please help me with this issue? I really need the f1_score metrics working for my project. I can not proceed without it.

Thx,

Balázs

**Comment by balazsgonczy** [comment]
So if you create a new child metrics class then is there a way to ever overwrite  or modify it? Because I couldn't after the error.

**Comment by Optimox** [comment]
Well glad to hear that you managed to make it work!

Feel free to reopen if needed on the 2nd issue.
