### ISSUE TITLE
SHAP library and TABNET

### ISSUE THREAD

**Issue by balazsgonczy** [dreamquark-ai/tabnet#388]
Dear Authors,

How can I compute a SHAP feature importance ranking bar graph on TABNET?

Kind regards,

Balázs

**Comment by balazsgonczy** [comment]
Please if you know any implementation for the current TABNET then don't hold it back! I am really in need of this tool.

**Comment by Optimox** [comment]
Hello @balazsgonczy,

Tabnet has its own explanations mechanism thanks to attention (have a look at the example notebooks).
So you probably don't need to use shapley on top of TabNet. If you absolutely want to do it I guess you'll need to use a model agnostic explanation which I think is available with SHAP.

This is out of scope so I'm closing it. Nevertheless don't hesitate to share your solution for others in this issue.
