### ISSUE TITLE
Install does not include augmentations so census example fails

### ISSUE THREAD

**Issue by parsifal9** [dreamquark-ai/tabnet#401]
Install does not include augmentations so census example fails

**What is the current behavior?**
```
conda install -c conda-forge pytorch-tabnet
```
then working through the census example https://github.com/dreamquark-ai/tabnet/blob/develop/census_example.ipynb I get
```
>>> from pytorch_tabnet.augmentations import ClassificationSMOTE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pytorch_tabnet.augmentations'
```

**Expected behavior**

expect the worked example to work

**Screenshots**

none

**Other relevant information:**
poetry version:  not using poetry
python version: 3.9.5 
Operating System: Linux (Ubuntu 18.04)
Additional tools: conda 4.13.0

**Additional context**

Some of the other worked examples fail the same way. Some (like the regression example) don't use pytorch_tabnet.augmentations and they work.

**Comment by Optimox** [comment]
Hello @parsifal9,

This is not a bug, augmentations exist only on the development branch.
You can specify to install the development with `!pip install "git+https://github.com/dreamquark-ai/tabnet.git@develop#egg=pytorch_tabnet" --upgrade`

The next release is coming soon.

**Comment by parsifal9** [comment]
thanks. Next time I will check the development branch first.
