### ISSUE TITLE
I found that "gpu" and "cpu" had a big impact on the results.

### ISSUE THREAD

**Issue by cc360** [dreamquark-ai/tabnet#413]
GPU：auc0.66
CPU：auc0.69

Is it because other parameters will change accordingly？

Why？thanks

**Comment by eduardocarvp** [comment]
Hello @cc360 ,

Switching from CPU to GPU does actually change some configurations. You can have more information here https://github.com/dreamquark-ai/tabnet/issues/345.

Let me know if this helps!
