### ISSUE TITLE
Handle/Imputing Missing Entries

### ISSUE THREAD

**Issue by TianyiPeng** [dreamquark-ai/tabnet#415]
## Feature request
In a lot of scenarios, the input table has missing values. Seems that the current algorithm cannot handle those missing values directly. 

The tabnet pre-training process should be able to handle the missing data (with a mask as an input) or be used to impute the missing data after the training. Any suggestion for this issue?

**Comment by Optimox** [comment]
Imputing missing values is a real challenge.

Masking an entry with attention is equivalent to fillna = 0, so I guess this gives you a simple fillna method, eventhough there is probably something smarter to do.

In the end I think it would be nice to accept missing values inside tabnet but the proposed method would probably be suboptimal so it's always better to think manually what to do with missing values.
