### ISSUE TITLE
KeyError: (Some random Number) for pandas/csv file

### ISSUE THREAD

**Issue by seanko29** [dreamquark-ai/tabnet#417]
**Describe the bug**

Hello. 
My issue is that I am getting key error when I use tabnet.fit(x_train, y_train) for scikit-learn way of doing it.
Also, if you do not use an eval set but only do clf.fit(x_train, y_train), should it work as well? 

Thank you in advanced :)

**What is the current behavior?**

I am getting keyerror. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/72428646/178195988-0de6ea77-3c92-45cb-bd5c-3bdf7414d244.png)

**Other relevant information:**
poetry version:  
python version: 
Operating System: 
Additional tools:

**Additional context**

**Comment by Optimox** [comment]
Input for tabnet should be numpy matrices, have you tried `X_train.values` ?

**Comment by seanko29** [comment]
X_train.values, y_train.values and same for the test set worked for me!
Thanks!
