### ISSUE TITLE
eval_metric is missing in Pretrainer

### ISSUE THREAD

**Issue by sooeun67** [dreamquark-ai/tabnet#419]
**Describe the bug**
`eval_metric` is not available in [**TabNetPretrainer.fit**](https://github.com/dreamquark-ai/tabnet/blob/4fa545da50796f0d16f49d0cb476d5a30c2a27c1/pytorch_tabnet/pretraining.py#L49) even though it is described as one of parameters -- seems like you forgot `eval_metric` to be included in parameters

**What is the current behavior?**
got an error ```TypeError: fit() got an unexpected keyword argument 'eval_metric'```

**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**

**Screenshots**

**Other relevant information:**
poetry version:  
python version: 
Operating System: 
Additional tools:

**Additional context**

<img width="686" alt="스크린샷 2022-07-12 오후 4 29 53" src="https://user-images.githubusercontent.com/32501921/178434013-17633209-b698-4713-9489-400e53d933c6.png">

**Comment by sooeun67** [comment]
Hey, thanks for the prompt reply!
I was hoping to have default metrics (such as `logloss`, `auc` for classifier) available during pretraining as well as custom metric [as documented](https://dreamquark-ai.github.io/tabnet/generated_docs/README.html?highlight=custom%20metric#default-eval-metric)

**Comment by Optimox** [comment]
The pretrainer is an unsupervised training, there is no target to predict, the model is trying to predict missing inputs it received. So both logloss or AUC does not make any sense.

Custom metric could be used but I think it's would be a minor improvement. What kind of unsupervised metric would you use ?

**Comment by sooeun67** [comment]
ah my bad -- you're right. I am not sure if using one of the traditional metrics of unsupervised learning, such as kmeans clustering, rand index, etc, is a proper way to evaluate pretraining either. 

What about having a module that compares/visualizes reconstructed x with original x ? My intention was to confirm the performance of pretrainer.

**Comment by Optimox** [comment]
It's an interesting topic, at the moment you can expect to have a 'working' reconstruction as long as the pretraining loss is bellow 1.

Feel free to propose some other methods in a PR to discus more concretely
