### ISSUE TITLE
How to utilise M1 GPU

### ISSUE THREAD

**Issue by rocket-yg** [dreamquark-ai/tabnet#430]
## Feature request
Is there any existing way to use the GPU on the M1 Apple Silicon for model training, since it is said that pytorch has made enhancements to utilise it.

**What is the expected behavior?**
None

**What is motivation or use case for adding/changing the behavior?**
Quicker Training

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by Optimox** [comment]
I have no idea how to make pytorch use M1-GPU, would be happy to make it M1 friendly if needed.

**Comment by chrislemke** [comment]
Isn't [this](https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/) a thing. Looks like it is still in beta. But looks like `mps` is simply another device: `backends.mps.is_available()`.
