### ISSUE TITLE
AssertionError: can only test a child process 

### ISSUE THREAD

**Issue by sonnguyen129** [dreamquark-ai/tabnet#433]
**Describe the bug**

Sometimes when I trained that model, after some epochs I cause that error

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/55862188/189348610-cf954502-926f-498c-a2b6-0086a14d1ec8.png)

**Other relevant information:**
poetry version:  
python version: 
Operating System: 
Additional tools:

**Additional context**

**Comment by Optimox** [comment]
Maybe you can try to set num_workers=0

**Comment by Optimox** [comment]
@sonnguyen129 do you have more information on your issue ?  Because I don't think I can help with so little information.

**Comment by sonnguyen129** [comment]
Hi @Optimox, I think I solved it, just set num_worker=0 as you said. Can you explain that warning? Thank you so much

**Comment by Optimox** [comment]
num_workers is the number of process trying to read lines of the matrices in the dataloader. If it's set too high for your computer configuration I guess there can be issues with parallel computing.

Glad that your problem is solved.
