### ISSUE TITLE
Add tensorboard logging

### ISSUE THREAD

**Issue by KAEYL98** [dreamquark-ai/tabnet#442]
## Feature request

**What is the expected behavior?**
Add support for tensorboard log files as an optional option to model parameters

**What is motivation or use case for adding/changing the behavior?**
Better tracking of different runs when tuning hyper parameters

**How should this be implemented in your opinion?**
Utilize existing torch.utils.tensorboard methods provided by pytorch

**Are you willing to work on this yourself?**
Not sure

**Comment by Optimox** [comment]
I think this would create an unnecessary dependency to the library. Logs for tabular data at each iteration have been enough for everyone when using XGBoost or any other model so I don't think it worth making things more complicated.
