### ISSUE TITLE
saving/loading tabnet classifier model

### ISSUE THREAD

**Issue by maymag** [dreamquark-ai/tabnet#452]
**Describe the bug**

**What is the current behavior?**
I'm unable to load a trained TabNetClassifier() saved model.  I used a custom evaluation metric during training. The model was "Successfully saved". There is no error when I try to load. It just loads nothing. I saved and loaded according to documentation. I

**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**
It should load a model but it's not.

**Screenshots**

**Other relevant information:**
poetry version:  
python version: Python 3.7.12
Operating System: "Ubuntu 20.04.4 LTS"
Additional tools:

**Additional context**

**Comment by Optimox** [comment]
Hello, I will definitely need more information in order to help you.

Can you share a minimal reproducible code and the error message you encounter ?
