### ISSUE TITLE
Torch version 2.0+ not supported in current release

### ISSUE THREAD

**Issue by zhanwuzhazha** [dreamquark-ai/tabnet#490]
Hi there, I recently tried to use Torch with version 2.0 or higher in the current release of the software, but I found that it doesn't seem to be supported. Torch version 2.0+ should be compatible, I encountered issues when trying to install and use it.

Could you please confirm whether Torch version 2.0+ is actually supported in the current release? If it is not supported, I suggest updating the documentation to reflect this.

Thank you for your help!

**Comment by pangshengwei** [comment]
yes please support torch2.0+

**Comment by mkleinbort-ic** [comment]
yes please

**Comment by cyclux** [comment]
+1 😃

**Comment by Optimox** [comment]
Can someone let me know what is the exact problem encountered here ?
When trying to pip install you have compatibility issues? or is it just that the library will not work properly if you have torch2.0 installed ?
