### ISSUE TITLE
Current version on conda-forge is 4.0 while 4.1 is already released

### ISSUE THREAD

**Issue by Sebge** [dreamquark-ai/tabnet#518]
Hi,
I just wanted to install your implementation via conda and noted that the version there is still 4.0. Since your changelog states that 4.1 comes with pytorch 2.0 support, I would be grateful if you could put the current version also on conda-forge (clearly, the current way-to-go is to install it via pypi, but that is suboptimal in a conda enviroment).
Best regards!

**Comment by Optimox** [comment]
@sugatoray Any chance you know how to do this ?

**Comment by sugatoray** [comment]
@optimox Should be doable, since PyTorch 2.0.0 is available in principle, on conda-forge channel. All we need is a PR updating the recipe (with successful build of the library in conda-forge channel). 

![image](https://github.com/dreamquark-ai/tabnet/assets/10201242/a8f0d17e-24de-45d5-bc6d-f821250ffd19)

**Comment by Optimox** [comment]
Ok, is there any chance you could take care of this? That would be very helpful for a lot of conda users!

**Comment by sugatoray** [comment]
@Optimox Yes, I can look into it. Will keep you posted here.

**Comment by Optimox** [comment]
Thank you, it's very much appreciated!

**Comment by Optimox** [comment]
is this resolved ? @sugatoray

**Comment by sugatoray** [comment]
Hi @Optimox, I am looking into it. Will share an update once it is taken care of. Thank you. 

> EDIT: The conda-forge version for pytorch-tabnet is the same as that on PyPI. `v4.1.0`

👉 Please check once from your end and close this issue if everything looks fine. Thank you. 

https://anaconda.org/conda-forge/pytorch-tabnet

**Comment by Optimox** [comment]
Thank you very much! Looks good to me!
