### ISSUE TITLE
Transfer learning, capability to change structure of model

### ISSUE THREAD

**Issue by DonCorle0ne** [dreamquark-ai/tabnet#520]
## Feature request
I wonder if it is possible to train a classification model with dataset 1, say 100 features, save the model and use it continue training on dataset 2, but with say 150 features, of which first 100 features are the same as dataset 1. 

**What is the expected behavior?**
Be able to save the model and expand the structure to do transfer learning

**What is motivation or use case for adding/changing the behavior?**
This gives user freedom to maintain a base model and explore new intelligence to add in as needed, not forced to train from scratch

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by Optimox** [comment]
As of my knowledge this is not feasible with any current machine learning algorithm, you need to retrain the model if you change the inputs.
