### ISSUE TITLE
Generate Embeddings for Tabular Data

### ISSUE THREAD

**Issue by Gaurav7888** [dreamquark-ai/tabnet#521]
## Feature request
Generate Embeddings For the Tabular data

**What is the expected behavior?**
We can get embeddings of tabular data

**What is motivation or use case for adding/changing the behavior?**
It can be used in several other use cases.

**How should this be implemented in your opinion?**
If tabnet is encoder-decoder type model then just throw the vector embeddings generated after encoder layer

**Are you willing to work on this yourself?**
No

**Comment by eduardocarvp** [comment]
The encoder layer returns `steps_out` which is then input to the decoder:

```
steps_out, _ = self.encoder(masked_x, prior=prior)
res = self.decoder(steps_out)
```

Is that what you mean by the vector of embedding generated?
