### ISSUE TITLE
Optimizing TabNet for Disease Classification with Continuous Audio Features

### ISSUE THREAD

**Issue by Yasich** [dreamquark-ai/tabnet#531]
Hello TabNet Developers,
Thank you very much for developing this method and sharing it.
I have a dataset that contains features extracted from the audio signal. My goal is to classify healthy and patient people. This dataset is tabular and each column contains features such as jitter, shimmer, etc. I have two questions that I would be very grateful if you could guide me. First question, considering the main nature of the data, can I still use the Tabnet architecture to analyze my data?
Second question: My data contains 27 features in the form of continuous numbers and there are no categorical variables. The 28th column is the target variable, which actually indicates the status of the disease and is marked with zero and one. I am confused. Can you help me what changes should I make in the code structure to make sure it works correctly?
@Optimox

**Comment by Optimox** [comment]
Yes you can try tabnet for your problem (but working directly on audio signal with mel spectrogram + CNN should work better).
You can simply follow this notebook tutorial to apply tabnet to your dataset: https://github.com/dreamquark-ai/tabnet/blob/develop/census_example.ipynb
