### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by ChiragChauhan4579** [dreamquark-ai/tabnet#533]
So I am trying this code and it gives me the error mentioned in title

BS=1024
MAX_EPOCH=101

N_D = 128
N_A = 32
N_INDEP = 1
N_SHARED = 1
N_STEPS = 3

unsupervised_model = TabNetPretrainer(
    optimizer_fn=torch.optim.Adam,
    optimizer_params=dict(lr=2e-2),
    mask_type='entmax' # "sparsemax"
)

unsupervised_model.fit(
    X_train=x_train.values,
    eval_set=x_test.values,
    pretraining_ratio=0.8,
)

I don't understand what is the problem here. The moment I remove eval_set the training works.

**Comment by Optimox** [comment]
Looks like you did not carefully read the documentation or look into an example notebook. Simply change to a list of np.array : `eval_set=[x_test.values]`
