### ISSUE TITLE
when I try to train with pretrained model loaded, kernel dies

### ISSUE THREAD

**Issue by nikhoj** [dreamquark-ai/tabnet#546]
I am trying to train a model after pretraining. whenever it reaches to last epoch it shows the final log message that best epoch was X .... and then keep running. After sometime the kernel dies. It happens always.

Could you please let me know if this is any mistake from my end? I was using in AWS Sagemaker.

**Comment by nikhoj** [comment]
when drop_last is set to 'True', this problem does not arise.

**Comment by Optimox** [comment]
Well that's weird, glad you found a solution to this problem.
