### ISSUE TITLE
Multitask regression use case

### ISSUE THREAD

**Issue by nikhildhinagar** [dreamquark-ai/tabnet#559]
Hello, I would like to utilize tabnet for a multitask regression problem, where multiple continuous targets are to be predicted. In the given example for multi regression (https://github.com/dreamquark-ai/tabnet/blob/develop/multi_regression_example.ipynb), the target is specified as 'target = ' <=50K'' like in the single regression example. Please advise on how i could adapt this for multiple target columns in the csv. Thanks in advance for your help.

**Comment by Optimox** [comment]
There is nothing to adapt, the regression example just uses a dataset with binary targets, but if your targets are not binary then the model will learn on non binary targets.
