### ISSUE TITLE
device in torch.nn.Module

### ISSUE THREAD

**Issue by mgrankin** [dreamquark-ai/tabnet#75]
Hello and thank you for your great work!

What was the idea behind passing `device` parameter to the constructor of `nn.Module` and storing it? I've never seen that pattern before in Pytorch.

**Comment by mgrankin** [comment]
I've removed `device` in the code here 
https://github.com/mgrankin/fast_tabnet/blob/master/02_tab_network.ipynb

**Comment by Hartorn** [comment]
Linked to #77
